### ISSUE TITLE
command 'extension.mdmath' not found

### ISSUE THREAD

**Issue by hxp33** [goessner/mdmath#1]
I install from the vscode extension list, when I use `ctrl+shift_.` , no response ,show me error `command 'extension.mdmath' not found
Close
Error`

**Comment by goessner** [comment]
Please try alternatively <kbd>ctrl+shift+p</kbd> and then type "Markdown+Math". It should list the installed extension then. If it does not appear in the list the installation process was not successful. Otherwise you can load the extension that way as a workaround. Hope that helps.

**Comment by hxp33** [comment]
![screenshot from 2016-12-01 14 51 06](https://cloud.githubusercontent.com/assets/7861326/20784519/ad9ab3fc-b7d5-11e6-975a-44cb0ecd7a10.png)
![screenshot from 2016-12-01 14 49 54](https://cloud.githubusercontent.com/assets/7861326/20784520/b0c5d6f6-b7d5-11e6-949d-ca9fbe93deb9.png)
Still can't work. I install it directly from vscode extensions market, not from source ,And vscode show me i install success.

**Comment by mrobakowski** [comment]
I seem to have solved the problem in my installation. @goessner, you should put the dependecies (at least those that are not included in vscode) in the dependencies section in the package.json. Katex isn't included in the package you ship to the marketplace and extension.js fails silently when requiring it. Thus, the extension.mdmath is never registered, causing the error.

**Comment by goessner** [comment]
@mrobakowski, thanks ... I put 
```
    "dependencies": {
        "markdown-it-katex": "^2.0.3"
    },
```
into `package.json`. Now everything works fine, if you install from command line via
```
cd  %USERPROFILE%\.vscode\extensions
git clone https://github.com/goessner/mdmath.git
cd mdmath
npm install
```
But it still does not work properly, if you install from within VS Code. It does, when you additionally do
```
cd  %USERPROFILE%\.vscode\extensions\goessner.mdmath-0.8.x
npm install
```
from the command line.

I sent an issue to the vscode team about that ...

https://github.com/Microsoft/vscode/issues/16368

I continue to work at resolving that problem.

Thanks also at @xiaopenghuang ...

**Comment by mrobakowski** [comment]
Hmm...
Did you check with ```vsce ls``` if katex is included? If so everything should be fine if you just build an extension package with ```vsce``` and publish that to the marketplace.

I found some info here: https://code.visualstudio.com/docs/extensions/patterns-and-principles#_using-nodejs-modules-with-extensions

**Comment by goessner** [comment]
yes .. I have been reading exactly that and also did `vsce ls` in my development folder. KaTeX as well as its necessary fonts are listed as included ... but ... obviously Katex dependencies (lodash, ...) are missing in that listing and at installation time in `node_modules` folder.

**Comment by goessner** [comment]
@xiaopenghuang , @mrobakowski ... I am confident in having successfully resolved this installation bug. I am interested, if it also works for you now or if there is possibly another issue,

Thanks ...

**Comment by mrobakowski** [comment]
@goessner Works for me, I even checked on another machine. 😄

**Comment by goessner** [comment]
Great .. thanks for coming back ..

**Comment by hxp33** [comment]
@goessner @mrobakowski  it works for me. thanks
