### ISSUE TITLE
Unable to open preview

### ISSUE THREAD

**Issue by Phantato** [goessner/mdmath#10]
I installed this extension and use `ctrl+shift+.`, but it shows  an error: 
```
"cannot open"Preview: Filename.md": Cannot read property 'document' of undefined.
```
How could I fix it?

**Comment by Phantato** [comment]
I found something useful.
The error occurs when I use the default preview firstly, and try to use the extension. I thought there may be a conflict.

**Comment by goessner** [comment]
I was not able to generate that error message. You might do me a favour and try it with next version.

Thanks
