### ISSUE TITLE
Need for documentation for Math and Geometry and other study fields

### ISSUE THREAD

**Issue by hwpplayer1** [goessner/mdmath#100]
### Summary

Need for documentation for Math and Geometry and other study fields

### Expected behavior

Searching for documentation within the extension

### Actual behavior

There is only a gif. Thanks for that. But i want to contribute for more.

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Code example

```md
Some markdown code ...

... with issues.
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: Trisquel GNU/Linux 9 ( Based on Ubuntu 18.04 ) with Linux-libre kernel
       VSCode version: August 2020 (version 1.49) 1.49.1
Markdown+Math version: 2.5.1
```
will be updated by getting feedback. Thanks!

**Comment by goessner** [comment]
i am not sure, what you want to have documented.

1. Using mdmath is documented here.
2. Using Markdown, see multiple docs on the web.
3. Using LaTeX math, see https://katex.org/docs/supported.html

Maybe this helps a little ...
https://goessner.github.io/mdmath/publication.html
