### ISSUE TITLE
Syntax colouring doesn't work on single dollars.

### ISSUE THREAD

**Issue by ericrbg** [goessner/mdmath#101]
### Summary

When trying to write KaTeX in single dollars, the syntax colouring does not work, and insteads displays everything in one colour.

### Expected behavior

The syntax colouring to work, as it does in double dollars.

### Steps to reproduce

1. Write maths in double dollars

![single dollars example](https://user-images.githubusercontent.com/37984851/95661563-34f4fc00-0b28-11eb-8bbf-97b65c85f58c.png)
![double dollars example](https://user-images.githubusercontent.com/37984851/95661565-3b837380-0b28-11eb-8939-b51837d7d174.png)

### Code example

```md
$s_i(v_j) = \begin{cases} c(v_j) & \text{if } (v_i, v_j) \in E \\ 0 & \text{otherwise.} \end{cases}$

$$ ABC DEF \sin(t) \begin{cases} \end{cases} $$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: Windows 10 Pro
       VSCode version: 1.50.0
Markdown+Math version: 2.5.1
```

**Comment by goessner** [comment]
works now as expected (version 2.6) ...
![grafik](https://user-images.githubusercontent.com/4902746/120468873-fe633e80-c3a1-11eb-87d0-dfd9783fa497.png)
