### ISSUE TITLE
Specific content triggers a crash

### ISSUE THREAD

**Issue by zhaouv** [goessner/mdmath#102]
if a markdown file contents `cd "$(dirname "$0")"` without quoting it. The preview will crush. Then you can not preview other normal markdown

example:
a.md
```
+ abc

cd "$(dirname "$0")"

+ def
```

Environment

```text
版本: 1.50.0 (user setup)
提交: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
日期: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

also test it in a virtual machine in VSC 1.50.1

may be a upstream bug

**Comment by goessner** [comment]
example above

```
+ abc

cd "$(dirname "$0")"

+ def
```
seems to work now with version 2.6
![grafik](https://user-images.githubusercontent.com/4902746/120469510-b85aaa80-c3a2-11eb-8511-ba07a015f29b.png)
