### ISSUE TITLE
Rendering of the \fcolorbox is broken

### ISSUE THREAD

**Issue by manifest** [goessner/mdmath#103]
### Summary

`\colorbox` & `\fcolorbox` renders its third argument as text, so we need to switch back to math mode with `$`. 
That doesn't work.

### Expected behavior

<img width="393" alt="Screen Shot 2020-10-26 at 22 21 09" src="https://user-images.githubusercontent.com/439058/97218305-93350680-17d9-11eb-9fd2-7d7be5b0a450.png">

### Actual behavior

<img width="268" alt="Screen Shot 2020-10-26 at 22 17 24" src="https://user-images.githubusercontent.com/439058/97217953-0db15680-17d9-11eb-8544-e93e728db4c1.png">

### Steps to reproduce

Enter the example below and open the preview.

### Code example

```markdown
$$
\fcolorbox{green}{white}{$x_{1}$}
$$
```

### Related links

[KaTeX documentation](https://katex.org/docs/supported.html#style-color-size-and-font)

### Environment

```text
Operating system: macOS 10.15.7
VSCode version: 1.50.1
Markdown+Math version: v2.5.1
```

**Comment by goessner** [comment]
`$$\fcolorbox{green}{black}{$\sqrt{x^2}$}$$` 

works as expected ... (version 2.6)
![grafik](https://user-images.githubusercontent.com/4902746/120468396-75e49e00-c3a1-11eb-9c6c-4049160734df.png)
