### ISSUE TITLE
linebreaks are not rendered

### ISSUE THREAD

**Issue by mmpataki** [goessner/mdmath#105]
### Summary
I am trying to put newlines using the features of the katex (\\ and \newline) but they are not working.
...

### Expected behavior
`\\` and `\newline` should render linebreaks
...

### Actual behavior
it's not rendering the linebreaks
...

### Steps to reproduce
Try this math expression
$$
(2i)^2 + (2j)^2 + (2k + 1)^2 \\
= 4i^2 + 4j^2 + 4k^2 + 4k + 1 \\
= 4(i^2 + j^2 + k^2 + k) +1 \\
= 4(n) + 1\\
= 2(2m) + 1\\
= 2(p) + 1
$$  

```text
     Operating system: Windows 10 (Ext running in the remote WSL)
       VSCode version: 1.5.1.1
Markdown+Math version: 2.5.1
```

**Comment by aaniin** [comment]
@mmpataki linebreaks work for me - see screenshot below. 
I'm using version Windows 10, VS Code 1.52.1, Markdown+Math v2.5.1 from marketplace. 
```
$$
(2i)^2 + (2j)^2 + (2k + 1)^2 \\
= 4i^2 + 4j^2 + 4k^2 + 4k + 1 \\
= 4(i^2 + j^2 + k^2 + k) +1 \\
= 4(n) + 1\\
= 2(2m) + 1\\
= 2(p) + 1\\
$$ 
```
![image](https://user-images.githubusercontent.com/20248857/102997319-19916e80-4525-11eb-8f9c-52200f0f392a.png)

**Comment by goessner** [comment]
... use double slashes `\\` as shown above ...
