### ISSUE TITLE
Autosave doesn't work without a reload of the extension.

### ISSUE THREAD

**Issue by MrF3lix** [goessner/mdmath#106]
### Summary

I installed the extension and used it for a while. Then I set the `mdmath.autosave` setting to `true` but nothing happened. Once I checked the code I saw that the `initWatching` function is only called when activating the extension. So once I disabled and re-enabled the extension it worked as exepcted.

### Expected behavior

When I adjust the `autosave` setting the `watcher` should be enabled directly. The same goes for disabling the setting.

### Actual behavior

Autosave is not enabled once the setting is set. Only after disabling and re-enabling of the extension.

### Steps to reproduce

1. Install the extension.
2. Use the extension.
3. Set the `mdmath.autosave` to `true`
4. Files that are not automatically saved as html.

### Environment

```text
Operating system: macOs Big Sur v11.1
VSCode version: v1.52.1
Markdown+Math version: v2.5.1
```

**Comment by MrF3lix** [comment]
If you want I can prepare a PR for this.

**Comment by goessner** [comment]
@MrF3lix ... thanks for finding,understanding and offering a fix for this behavior.

It would be great, if you can do a PR for this. Otherwsie I would extend the docs for the need to disable and re-enable the extension in that case.

thanks

--
sg

**Comment by goessner** [comment]
Commented in FaQ's ...

**Comment by traits** [comment]
> Commented in FaQ's ...
>> Be sure to have closed and opened VSCode again after having changed settings.

This doesn't work, and neither does any other combination of enabling/disabling/reloading/changing the Markdown file inbetween. The manual `Ctrl K,` is unaffected.

System Win10, VScode 1.66 portable
