### ISSUE TITLE
When I save MD document to HTML document, the `code block language highlighting` function doesn't work properly.

### ISSUE THREAD

**Issue by hustnzj** [goessner/mdmath#109]
### Summary
When I save MD document to HTML document, the `code block language highlighting` function doesn't work properly.
...

### Expected behavior
![image](https://user-images.githubusercontent.com/27875723/115978754-6741e480-a5b4-11eb-99fa-882cc41ad855.png)

...

### Actual behavior
![image](https://user-images.githubusercontent.com/27875723/115978808-cd2e6c00-a5b4-11eb-9de3-ca72ee281f28.png)

...

### Steps to reproduce

1. type the .md
2. in vscode, `command + shift + P`, and type the command as below:
![image](https://user-images.githubusercontent.com/27875723/115978912-4037e280-a5b5-11eb-84e3-2c25c5a8139d.png)

3. Open the output html in the browsers (chrome, firefox, safari etc)

### Code example

```md
$a$  
$\varphi$  
$1+1=2$  
$1+1<3$
```js
document.write('Hello, world')
```

### The reason I guess
Open the `console` panel of the browsers, I found the error tip: 
```
Refused to apply style from 'https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/lib/index.min.js' because its MIME type ('application/javascript') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
And I found the link src tag is used for the `https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/lib/index.min.js`. Why is it not script tag?
![image](https://user-images.githubusercontent.com/27875723/115979101-788bf080-a5b6-11eb-89c6-533d480cdd02.png)

I tried to use the script tag instead of the link one, but still got this error as below:
![image](https://user-images.githubusercontent.com/27875723/115979190-1da6c900-a5b7-11eb-9b53-245894be5376.png)
![image](https://user-images.githubusercontent.com/27875723/115979228-4b8c0d80-a5b7-11eb-9572-731a931c2233.png)

I tried to modify the `extension.js` in the extension root menu, but still didn't work.
![image](https://user-images.githubusercontent.com/27875723/115979316-d3721780-a5b7-11eb-85e0-a8246cfbf548.png)

### Environment

```text
     Operating system: macOS Big Sur
       VSCode version: 1.55.2
Markdown+Math version: 2.5.1
```

**Comment by goessner** [comment]
Link to `highlight.js` has become invalid.

Works again with mdmath version 2.6.
