### ISSUE TITLE
Support math inside blockquotes

### ISSUE THREAD

**Issue by Phantato** [goessner/mdmath#11]
### Summary

It seems that the parser can't recognize the display math inside a blockquotes starting by '>'

### Code example

```md
    > some content
    > $$
    > \begin{aligned}
    > a\cdot(x+y)&=a\cdot x+a\cdot y  \\
    > x+(y+z)&=(x+y)+z  \\
    > x+y&=y+x  \\
    > \end{aligned}
    > $$
```

the html of the preview shows
```html
<p>some content<br>
$$
\begin{aligned}
a\cdot(x+y)&amp;=a\cdot x+a\cdot y  \
x+(y+z)&amp;=(x+y)+z  \
x+y&amp;=y+x  \
\end{aligned}
$$</p>
````

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: Win10
       VSCode version: 1.9.1
Markdown+Math version: 1.1.0
```

**Comment by goessner** [comment]
thanks for raising that issue. 

Blockquote bug removed now. Will be available with next version (publishing today or tomorrow).

Please note: 

You need to write multiline formulas in blockquotes on a single line then, so that no '>' appear between $$..$$.

**Comment by Phantato** [comment]
It works to write them on a single line, though looks bad. Anyway thanks~

**Comment by gusbemacbe** [comment]
I have still this problem. This bug still insists, @goessner. Check the screenshot. 

![screenshot](https://user-images.githubusercontent.com/2257024/38847228-f47233fe-41d6-11e8-8d21-011af8d2d56c.png)

– VSCode Insiders 1.23
– macOS 10.13.3 and Ubuntu 16.04
– markdown-it-math 2.2.1
