### ISSUE TITLE
Multiline queations  with utf-8 characters ahead does not render correcly.

### ISSUE THREAD

**Issue by sandyUni** [goessner/mdmath#111]
### Summary

Multiline queations  with utf-8 characters ahead does not render correcly.
...

### Expected behavior
the source code of 

![image](https://user-images.githubusercontent.com/3823826/119595922-e4a98080-be10-11eb-8e84-83dd60cf33a2.png)

should be 
![image](https://user-images.githubusercontent.com/3823826/119595982-00148b80-be11-11eb-9314-51812ab69648.png)

### Actual behavior
the equation is not rendered
![image](https://user-images.githubusercontent.com/3823826/119596011-0a368a00-be11-11eb-9368-d28422515ebd.png)

### Code example

```md
这样
$$
so(3)=\{\phi \in R^3,\ \mathbf{\Phi}=\phi^\wedge \in \mathbb{R}^{3\times 3}\}
$$
```
However 

```md
这样

$$
so(3)=\{\phi \in R^3,\ \mathbf{\Phi}=\phi^\wedge \in \mathbb{R}^{3\times 3}\}
$$
```
will be rendered correctly.

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system:  whatever
       VSCode version: 1.56.2
Markdown+Math version: 2.5.0
```

**Comment by goessner** [comment]
it is the same with non-utf8 text ... so 
```
non-utf8
$$
so(3)=\{\phi \in R^3,\ \mathbf{\Phi}=\phi^\wedge \in \mathbb{R}^{3\times 3}\}
$$
```
also behaves the same.

This basically is a constraint from markdown-it, as display math requires a newline in order to be recognized as a new block element.

But surprisingly ...
```
这样 $$so(3)=\{\phi \in R^3,\ \mathbf{\Phi}=\phi^\wedge \in \mathbb{R}^{3\times 3}\}$$ 这样
```
... written alltogether on a single line works due to new Pandoc  compatibility ... try it out.
