### ISSUE TITLE
Commutative diagrams are not supported

### ISSUE THREAD

**Issue by nablatensor** [goessner/mdmath#112]
### Summary

KATEX supports commuative diagrams. But in mdmath it seems not to be integrated.

### Expected behavior

The code
$$
\begin{CD}
   A @>a>> B \\
@VbVV @AAcA \\
   C @= D
\end{CD}
$$
shall render a commutative diagram.

### Actual behavior

No commutative diagrams

### Code example

```md
$$
\begin{CD}
   A @>a>> B \\
@VbVV @AAcA \\
   C @= D
\end{CD}
$$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)
* https://katex.org/docs/supported.html

### Environment

```text
     Operating system: windows 10
       VSCode version: 1.56.2
Markdown+Math version: 2.51
```

**Comment by goessner** [comment]
hmm ... thanks for this hint ... in fact it works already with my new version of markdown-it-texmath 2.5.5.

![grafik](https://user-images.githubusercontent.com/4902746/120101757-e2fcf700-c147-11eb-9a5b-c61137b5aab7.png)


So it will also work in mdmath, which will include an update of katex ... due in some days.
