### ISSUE TITLE
Issue with custom macros

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [goessner/mdmath#113]
### Summary
From around yesterday, custom macros suddenly stopped working.
...

### Expected behavior
Custom macros defined in `settings.json` should work in markdown documents.
...

### Actual behavior
None of them work, not even after removing "problemating" ones and testing \Q for \mathbb{Q} for example (with appropriate number of backslashes). I've tried reinstalling, reloading, to no avail.
...

### Steps to reproduce

1. Add custom macro to `settings.json`
2. Reload extension
3. Use custom macro in maths mode (only red command name shows up)

### Code example

```json
"mdmath.macros": {
        "\\Q": "\\mathbb{Q}"
}
```

**Comment by goessner** [comment]
... it was a bug with macros user settings ... fixed with version 2.7.4 ...

thanx
