### ISSUE TITLE
Macros do not work 

### ISSUE THREAD

**Issue by rjmigliori** [goessner/mdmath#114]
### Summary

The macro example from the Readme is not working. Identical to [issue 63](https://github.com/goessner/mdmath/issues/63). 

### Expected behavior

Preview without errors.

### Actual behavior

Red symbols `\RR` and `\vek`. Also `\R` renders mathbb{R} correctly, while `\RR` does not.

### Steps to reproduce

1. Add example config to settings.json
2. Restart VS Code just in case
3. Open existing workspace. 
4. Open existing .md file. 
5. Write some example latex code. 
6. Open markdown preview. 

### Code example
1. `settings.json` section 
```
    "mdmath.macros":{
        "\\RR":"\\mathbb{R}",
        "\\vek": "{\\begin{pmatrix}#1\\\\#2\\end{pmatrix}}",
        "\\test":"2+2"
    },
```

2. `.md` file test section
```
\texttt{\textbackslash R \textbackslash RR \textbackslash test \textbackslash vek} \Rightarrow \R \RR \test \vek
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system:  Windows 10 Enterprise x64
       VSCode version: 

    Version: 1.57.0 (user setup)
    Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
    Date: 2021-06-09T17:18:42.354Z
    Electron: 12.0.9
    Chrome: 89.0.4389.128
    Node.js: 14.16.0
    V8: 8.9.255.25-electron.0
    OS: Windows_NT x64 10.0.18363

Markdown+Math version: 2.7.4
```

**Comment by goessner** [comment]
Be sure to have ...
* version 2.7.4 installed
* closed and opened VSCode again after having changed settings.

For me 

```md
Vectors in $\RR^2$ have a shape of

$$\vek{x}{y}$$
```
gives
![grafik](https://user-images.githubusercontent.com/4902746/122337776-165cc580-cf3f-11eb-9996-d55ac46b051d.png)

btw: KaTeX now supports `\R` natively, so macro `\RR` makes sense only for demonstration reasons.

**Comment by rjmigliori** [comment]
Simply does not work for me, on two different computers too. Maybe it's an interaction with one of my installed extensions? 

    ```math
    \RR
    ```
    
    $\RR$
    
    $$
    \RR
    $$

Produces 

![image](https://user-images.githubusercontent.com/22944226/122441303-a9572900-cf5a-11eb-91db-6082bac98f7a.png)

`settings.json` section:
```
    "mdmath.delimiters": "gitlab",
    "mdmath.macros":{
        "\\RR":"\\mathbb{R}",
        "\\vek": "{\\begin{pmatrix}#1\\\\#2\\end{pmatrix}}",
        "\\test":"2+2"
    },
```

Extensions 
![image](https://user-images.githubusercontent.com/22944226/122441724-136fce00-cf5b-11eb-8bdd-ea1a0888da41.png)

**Comment by goessner** [comment]
hmm ... please deactivate all markdown related extensions ... temporarily ...

**Comment by rjmigliori** [comment]
Interesting, it's one of the extensions. Working on figuring out which one right now. 

    ```math
    \RR
    ```
    
    $\RR$
    
    $$
    \RR
    $$

Produces 
![image](https://user-images.githubusercontent.com/22944226/122462739-2e017180-cf72-11eb-94d8-83173230c10a.png)

Not sure why $\RR$ isn't working, but, progress?

**Comment by rjmigliori** [comment]
It's the [Markdown All In One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension. 

Ugh I bet it's this, right in the Readme: 

    Please use Markdown+Math for dedicated math support. Be sure to disable math.enabled option of this extension.

**Comment by rjmigliori** [comment]
Fixed. 
Code:

    ```math
    \RR \\
    \vek{x}{y} \\
    \test \\
    ```
Produces:
![image](https://user-images.githubusercontent.com/22944226/122465117-edefbe00-cf74-11eb-859d-e1fa6864e185.png)

Settings:

      "markdown.extension.math.enabled": false, //<- This fixes the macro issue
      "mdmath.delimiters": "gitlab",
      "mdmath.macros":{
          "\\RR":"\\mathbb{R}",
          "\\vek": "{\\begin{pmatrix}#1\\\\#2\\end{pmatrix}}",
          "\\test":"2+2"
      },

Sorry for the trouble! Can close this, I think.

**Comment by goessner** [comment]
Thanks for successfully investigating this. Can you please do me a favor and raise an analog issue regarding macro collision there, while referencing your reproducable steps here ... thanks.

**Comment by rjmigliori** [comment]
I'd be happy to do that, but I'm not exactly clear on what you mean? Could you clarify more precisely what you'd like me to do?

**Comment by goessner** [comment]
don't worry ... I did it by myself ... thanks again.

**Comment by rjmigliori** [comment]
> don't worry ... I did it by myself ... thanks again.

I have another problem, but I wanted to ask you about it before opening a whole issue. Is there any way to get latex macros to render with the markdown file uploaded to gitlab/github? I'm getting the error "There was an error rendering this math block," I assume because gitlab doesn't know how to interpret the macros without them being defined anywhere. Not sure how to resolve this, or if it's even possible?

**Comment by goessner** [comment]
hmm ... macros are resolved in VSCode Markdown via mdmath via markdown-it-texmath via KaTeX. GitLab should have a completely different math engine. If that doesn't support macros, you are lost. GitHub doesn't have a math engine at all.

The only way I know is working, is to export HTML from mdmath to GitHub pages or something similar with GitLab.

**Comment by rjmigliori** [comment]
> hmm ... macros are resolved in VSCode Markdown via mdmath via markdown-it-texmath via KaTeX. GitLab should have a completely different math engine. If that doesn't support macros, you are lost. GitHub doesn't have a math engine at all.
> 
> The only way I know is working, is to export HTML from mdmath to GitHub pages or something similar with GitLab.

That's what I figured. How do you get github to render html (I looked into it a bit online but I'm wondering what your approach is)?

**Comment by afinedog** [comment]
I have an another trouble:  MPE(markdown preview enhanced) doesn't support the macros. And it works when I disable it.
