### ISSUE TITLE
Conflict with microJam

### ISSUE THREAD

**Issue by klawr** [goessner/mdmath#115]
### Summary
This extension can not be used together with [microjam](https://github.com/goessner/microjam) anymore, because the
`insertToc` command introduced in c208deba86f958b5e835fc1790d7a2fcf01a4e65 has a name-conflict, since *microJam* already has a command named `insertToc`.

### Expected behavior
Should have no conflict.

### Actual behavior
Has conflict.

### Steps to reproduce

1. Try to start microJam in DebugMode
2. Go to qualified Markdown file.
3. Observe following message:
![image](https://user-images.githubusercontent.com/16281695/122380154-deb64380-cf67-11eb-96c7-227533e4de0a.png)

### Code example

* Not applicable

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)
* [microjam](https://github.com/goessner/microjam)

### Environment

```text
    Operating system: Windows 10 Pro 21H1
    VSCode version: 1.57.0
    Markdown+Math version: 2.6+
```

**Comment by goessner** [comment]
Fixed with version 2.7.5 by renaming `extension.insertToc` to `extension.insertToC` ... thanks. Publication will last some time though.

For temporary solution please inject

* `package.json`
* `extension.js`

from this repo into

`\Users\<user>\.vscode\extensions\goessner.mdmath-2.7.4
