### ISSUE TITLE
Can you support ```math Syntax?

### ISSUE THREAD

**Issue by anrichter** [goessner/mdmath#14]
### Summary

I use Markdown and VS Code to write documentation which is rendered online on a git repository in GitLab. 
In the documentation i have to use math. And now i have a conflict in syntax for math.

With your Extension i have to use $$...$$ syntax for a preview of the formula and in GitLab i have to use the ```math Syntax to render formulas with KaTeX.

It is possible to add the ```math Syntax to your Extension so i can use it in Preview and in GitLab rendering?

### Expected behavior

```math
a^2+b^2=c^2
```

Should be rendered as a formula in preview

### Actual behavior

```math
a^2+b^2=c^2
```
Is rendered as normal Code block in Preview

### Steps to reproduce

1. Create an empty MarkDown File in VS Code
2. Add the following to the File:
```math
a^2+b^2=c^2
```
3. Open Markdown+Math Preview

### Related links

* [GitLab Math](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md#math)

### Environment

```text
     Operating system: Windows 10
       VSCode version: 1.9.1
Markdown+Math version: 1.2.4
```

**Comment by goessner** [comment]
Hello Andreas,

in fact I am thinking about the ability to allow other delimiters beneath the dollars. So in LaTeX `\[...\]` and `\(...\)` are the default delimiters for display and inline math.

As a solution I tend here to let users configure delimiters with their user settings. Quite not sure, if it is sufficient to only specify the delimiter pair, or if we need to specify complete regular expressions here.

So I need to do some tests and .. sorry .. you need to wait a while for one of next versions. No idea which release, but your feature request might be helpful here.

Thanks

**Comment by anrichter** [comment]
Hi Stefan,

that's sounds good. 
For the meantime i have a solution. I write the math with VS Code in $$ - pairs until it is finished and then i replace the $$ signs with ```math.
Not the best solution but it works for the moment. So i can wait for one of the next release of MdMath.

Thank you for your quick response and all the works here :)

Greetings,
Andreas

**Comment by goessner** [comment]
Andreas,

finally implemented user configurable delimiters (gitlab style also)

![grafik](https://user-images.githubusercontent.com/4902746/27052240-61221278-4fb9-11e7-8b04-1833059c377e.png)

See [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) for more info.

This will land in `mdmath` with upcoming June release of vscode.
