### ISSUE TITLE
Error using `Clip Markdown+Math to HTML`

### ISSUE THREAD

**Issue by QuantumLiu** [goessner/mdmath#19]
### Summary

Can't use `Clip Markdown+Math to HTML`

### Expected behavior

press `Ctrl+Shift+P` and run the command  `Clip Markdown+Math to HTML` and paste HTML sources to a .html file
### Actual behavior
pressed `Ctrl+Shift+P` and run the command  `Clip Markdown+Math to HTML` ,nothing happened,clipboard is still blank.
### Environment

```text
     Operating system: Win 10
       VSCode version: 1.12.1
Markdown+Math version: 1.2.7
```

**Comment by goessner** [comment]
Please try again version 1.2.9

**Comment by TonySFU** [comment]
I found this error in version 1.2.9, when markdown file is too long("let html" is a large object).
So short markdown file will pass this function, large markdown file will return a error('Running the contributed command '${id}' failed);

I am working on a solution right now.

**Comment by floatdrop** [comment]
I guess we are hitting [limit on arguments length in Windows](https://mcuoneclipse.com/2015/03/29/solving-the-8192-character-command-line-limit-on-windows/), this [PR](https://github.com/sindresorhus/win-clipboard/pull/2) should fix this issue.

**Comment by ghost** [comment]
I meet the same question. It happened when I write over line 80. than it's doesn't work.
     Operating system: Win 10
       VSCode version: 1.14.0
Markdown+Math version: 1.2.9

**Comment by goessner** [comment]
`mdmath` uses the most recent version of `clipboardy` as of release 2.0.

Should work now as expected.

thanks
