### ISSUE TITLE
preview does not render math, html output does

### ISSUE THREAD

**Issue by devalaya** [goessner/mdmath#2]
When taking the example file 'triangle.md' in the package, 'Markdown+Math as HTML' produces html output that renders (almost) correctly in the browser (chrome in my case).
However, the preview window does not render the math at all:
<img width="1135" alt="screen shot 2016-12-09 at 17 02 32" src="https://cloud.githubusercontent.com/assets/8107437/21055339/57d44de0-be31-11e6-9af6-089d6c7ccca7.png">

VSCode 1.7.2 on macos.

**Comment by goessner** [comment]
@devalaya : What does your closing mean ... problem solved ... ?
