### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by yd278** [goessner/mdmath#20]
### Summary
Line 3 in `mdmath.css`, i.e. `body { font-family: serif !important; }`  overwrote the font-family in `github-markdown.min.css`.

Attached a screenshot showing the difference between previews supplied by vscode and mdmath
![screenshot](https://cloud.githubusercontent.com/assets/23385935/26290858/74ea5c66-3ea2-11e7-8ee3-98d687832ca0.png)

**Comment by goessner** [comment]
Do you mean by *error* the fact, that ...

* `font-family` is set to `serif` ?
* the KaTeX parse errors ?

In the first case, research papers usually prefer that. So I have done that also. Hmm ... I don't know exactly now, why I added the `!important` directive here ... but I can remember that it was important somehow.

In the second case, we obviously need to escape the dollars in the list, if we treat the `readme.md` here as a document containing math formulas ... which it is not.

I tested  `readme.md`  with the next (unpublished) version of mdmath, which works fine here.

Thanks.
