### ISSUE TITLE
Failed to use customized CSS

### ISSUE THREAD

**Issue by csujedihy** [goessner/mdmath#21]
### Summary
Failed to use customized CSS
...

### Expected behavior
Apply any user CSS file on md preview
...

### Actual behavior
Nothing is changed after setting customized CSS
...

### Steps to reproduce

set customized CSS in workspace or user settings.

### Environment

```text
     Operating system: OSX 10.12
       VSCode version:1.12.2
Markdown+Math version: latest from marketplace
```

**Comment by csujedihy** [comment]
I currently comment `body { font-family: serif !important; }` in mdmath.css to make it work as my expectation since it changes all text's font to serif.

**Comment by timedreamer** [comment]
I had the same issue. And mdmath renders different font compared with naive markdown render. Any ideas?

[Update]: I change the `font-family` to Sans-serif in mdmath.css file. Now, it looks better. Thanks.

**Comment by goessner** [comment]
@csujedihy,  @timedreamer : 
hmm ...  I intended to offer a style (serif font, tables and images centered ...) which is often required for homeworks, theses and research papers.

But your issues show me, that this might be too restrictive  ... so I am considering now to reduce the styling to the minimum necessary for rendering the math.

All other styling can finally go into custom stylesheets, which are supported by mdmath .. what do you think?

Thanks

**Comment by csujedihy** [comment]
I agree that all other styling can finally go into custom stylesheets. That is awesome!

**Comment by timedreamer** [comment]
Either way works for me. Thanks
