### ISSUE TITLE
Can't input Chinese or other unicode word

### ISSUE THREAD

**Issue by 598753468** [goessner/mdmath#23]
Is there any ways to solve it?

**Comment by goessner** [comment]
Please add example markup, where it fails.

See #16 for having updated KaTeX properly resolving Asian characters.

**Comment by 598753468** [comment]
When I input
```
$$
f(x)=
\left\{\begin{matrix}
\frac{255}{90}(x-30) & 30<x<120 \\ 
\frac{255}{90}(30-x) & 0<x\leqslant30 或 120\leqslant x\leqslant180
\end{matrix}
\right. 
$$
```
There is an error message in the preview window:
> ParseError: KaTeX parse error: Expected & or \\ or \end at position 104: …0

While I replaced "`或`" with "`or`", it can be displayed correctly.
```
$$
f(x)=
\left\{\begin{matrix}
\frac{255}{90}(x-30) & 30<x<120 \\ 
\frac{255}{90}(30-x) & 0<x\leqslant30 or 120\leqslant x\leqslant180
\end{matrix}
\right. 
$$
```
Other simple examples:
`$$v_{地}$$` got 

> ParseError: KaTeX parse error: Expected '}', got '地' at position 4: v_{地̲}

`$$v_{ground}$$` is correct.

---
mdmath:1.2.9
vscode:1.13.1
OS:ubuntu16.04

**Comment by goessner** [comment]
You should have read  #16 more carefully:

In KaTeX version 0.6.0, CJK characters (Chinese, Japanese, and Korean characters) inside \text blocks caused ParseErrors. The recent KaTeX version (0.7.1) has resolved this.

So simply use 

$$v_{\text 地}$$ 

instead.
