### ISSUE TITLE
copy and pasting the test table into a .md file fails

### ISSUE THREAD

**Issue by johndpope** [goessner/mdmath#24]
### Summary
copy and pasting the test table into a .md file fails
...

### Expected behavior
tests should pass.
...

### Actual behavior
Markdown+Math Tests

i	valid	src	render	comment 0	😊	1+1=21+1=2	1+1=21+1=2

simple equation starting and ending with numbers. 1	😊	1+1<31+1<3	1+1<31+1<3

simple equation including special html character. 2	😊	xx	xx

inline equation with single character 3	😊	\varphiφ	\varphiφ

inline equation with single greek character 4	😊	You get 3$ if you solve 1+21+2	You get 3$ if you solve 1+21+2

use of currency symbol 5	😊	If you solve 1+21+2 you get $3	If you solve 1+21+2 you get $3

use of currency symbol 6	😊	\frac{1}{2}
​2
​
​1
​​ 	\frac{1}{2} ​2 ​ ​1 ​​

inline fraction 7	😊	\begin{pmatrix}x\\y\end{pmatrix}(
​x
​y
​​ )	\begin{pmatrix}x\y\end{pmatrix}( ​x ​y ​​ )

inline column vector 8	😊	{\tilde\bold e}_\alpha
​e
​~
​​ 
​α
​​ 	{\tilde\bold e}_\alpha ​e ​~ ​​ ​α ​​

inline bold vector notation 9	😊	a^{b}a
​b
​​ 	a^{b}a ​b ​​

exponentiation 10	😊	a^*ba
​∗
​​ b with a^*a
​∗
​​ 	a^*ba ​∗ ​​ b with a^*a ​∗ ​​

conjugate complex 11	😊	{e}_xe
​x
​​ 

e\_\\alphae
​α
​​ 
{e}_xe ​x ​​

e_\alphae ​α ​​

greek index 12	😊	ParseError: KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲c{\bold e}_x = …$ c{\bold e}_x = a{\bold e}_\alpha - b\tilde{\bold e}_\alphace ​x ​​ =ae ​α ​​ −b ​e ​~ ​​ ​α ​​

underline tests 13	😊	a1+1=21+1=2 1+1=21+1=2b cxxd	a1+1=21+1=2 1+1=21+1=2b cxxd

non-numeric character before opening $ or after closing $ or both is allowed. 14	😊	xx $ xx $

following dollar character '$' is allowed. 15	😊	xx yy	xx yy

consecutive inline equations. 16	😊	ParseError: KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲1+1=2$ 1+1=21+1=2

display equation on its own single line. 17	😊	$$ 1+1=2 $$	1+1=2 1+1=2

display equation with line breaks. 18	😊	$$\begin{matrix} f & = & 2 + x + 3 \ & = & 5 + x \end{matrix}$$ \begin{matrix} f & = & 2 + x + 3 \\ & = & 5 + x \end{matrix} ​f ​ ​​ ​= ​= ​​ ​2+x+3 ​5+x ​​

multiline equation. 19	😊	$$\begin{pmatrix}x_2 \ y_2 \end{pmatrix} = \begin{pmatrix} A & B \ C & D \end{pmatrix}\cdot \begin{pmatrix} x_1 \ y_1 \end{pmatrix}$$	\begin{pmatrix}x_2 \\ y_2 \end{pmatrix} = \begin{pmatrix} A & B \\ C & D \end{pmatrix}\cdot \begin{pmatrix} x_1 \\ y_1 \end{pmatrix}( ​x ​2 ​​ ​y ​2 ​​ ​​ )=( ​A ​C ​​ ​B ​D ​​ )⋅( ​x ​1 ​​ ​y ​1 ​​ ​​ )

vector equation. 20	😊	ParseError: KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲f(x) = x^2 - 1$ (1) f(x) = x^2 - 1f(x)=x ​2 ​​ −1 (1)

display equation with equation number. 21	😊	codea-ba−b	codea-ba−b

inline equation following code section. 22	😊	``` code

<section><eqn><span class="katex-display"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>a</mi><mo>+</mo><mi>b</mi></mrow><annotation encoding="application/x-tex">a+b</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.69444em;"></span><span class="strut bottom" style="height:0.77777em;vertical-align:-0.08333em;"></span><span class="base displaystyle textstyle uncramped"><span class="mord mathit">a</span><span class="mbin">+</span><span class="mord mathit">b</span></span></span></span></span></eqn></section>
	
code

a+ba+b

equation following code block.
23	😊	```
code
a+ba+b
(1)
code

a+ba+b (1)

numbered equation following code block. 24	😊	1. 1+21+2 2. 2+32+3 1. 3+43+4

1+21+2

2+32+3

3+43+4

Equations in list. 25	😊	\sum_{i=1}^n∑
​i=1
​n
​​ 	\sum_{i=1}^n∑ ​i=1 ​n ​​

Inline sum. 26	😊	ParseError: KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲\sum_{i=1}^n$ \sum_{i=1}^n ​i=1 ​∑ ​n ​​

Sum without equation number. 27	😊	ParseError: KaTeX parse error: Expected 'EOF', got '$' at position 1: $̲\sum_{i=1}^n$ (2)	\sum_{i=1}^n ​i=1 ​∑ ​n ​​ (2)

Sum with equation number. 28	😊	$${\bold e}(\varphi) = \begin{pmatrix} \cos\varphi\\sin\varphi \end{pmatrix}$$ (3)	{\bold e}(\varphi) = \begin{pmatrix} \cos\varphi\\\sin\varphi \end{pmatrix}e(φ)=( ​cosφ ​sinφ ​​ ) (3)

equation number always vertically aligned. 29	😊	> see a = b + ca=b+c

c^2=a^2+b^2c
​2
​​ =a
​2
​​ +b
​2
​​ 
(2)
c^2=a^2+b^2c
​2
​​ =a
​2
​​ +b
​2
​​ 
see a = b + ca=b+c

c^2=a^2+b^2c ​2 ​​ =a ​2 ​​ +b ​2 ​​ (2)

c^2=a^2+b^2c ​2 ​​ =a ​2 ​​ +b ​2 ​​

equations in blockquote. 30	😡	3$1+1=2$ $1+1=2$4 5$x$6	3$1+1=2$ $1+1=2$4 5$x$6

numeric character before opening $ or after closing $ is not allowed. 31	😡	$ $ $ x$ $x $	$ $ $ x$ $x $

whitespace character after opening $ or before closing $ is not allowed. 32	😡	$1+1=2$ $1+1=2$	1+1=21+1=2 1+1=21+1=2

escaped dollars '$' are interpreted as dollar '$' characters.+ 33	😡	1+1=21+1=2$1+1=2$	1+1=21+1=2$1+1=2$

at least one character (whitespace) is required between two inline formulas. 34	😡	$1+1= 2$	$1+1= 2$

line break in inline equation is not allowed.
...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Code example

```md
Some markdown code ...

... with issues.
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: ___
       VSCode version: ___
Markdown+Math version: ___
```

**Comment by goessner** [comment]
Hi John,

nice idea .. I never tried this. I will have a look into it, but would like to postpone that until after the next major update.

Thanks for your effort

Stefan

**Comment by johndpope** [comment]
hi @goessner - fyi - I found these  projects = im2latext 
https://github.com/search?utf8=%E2%9C%93&q=im2latex&type=

They have an training extensive which includes   a list 12mb - of latex formulas
  -see here  im2latex_formulas.lst
https://zenodo.org/record/56198#.WVVXzBIrKgx

**Comment by johndpope** [comment]
also -fyi -  there's a treasure trove of machine learning latex functions here https://github.com/soulmachine/machine-learning-cheat-sheet

**Comment by johndpope** [comment]
closing this
