### ISSUE TITLE
It just does not work for me

### ISSUE THREAD

**Issue by ProkopHapala** [goessner/mdmath#25]
Are there any requirements to make it work besides just to install it and activate?

- I can see preview, but the equations are not rendered - just their source code. Rest of markdown is rendered properly (e.g. headers, lists)
- the keyboard shortcuts `Ctrl+Shift+.` or `Ctrl+Shift+P` does nothing.

possible causes:

 - Are there any issues on linux (I have Ubuntu 16.04 LTS 64bit ) ?
 - Can it interfere with some other packages? ( I installed many Markdown plugins into visual studio code recently ). For example markdown-auto-preview
 - are there some steps which have to be done to activate it? (e.g. edit my user settings) ?

**Comment by psukys** [comment]
Hey, can you add your workflow, expected result, and result that you got?

**Comment by ProkopHapala** [comment]
Hi. I did nothing sophisticated - I'm very new to visual studio code. 

basically I just 
 - installed `goessner.mdmath` plugin
 - restarted visual studio code
 - open `.md` file.
 - press `Ctrl+Shift+.` or `Ctrl+Shift+P`  ... nothing happens
 - when I activate "Auto-Open Markdown Preview" plugin it will open a preview, but this preview does not render any math equations
 - Once it happened that "Markdown Preview Enhanced" opened, which rendered math equation properly, but I'm unable to run it again

I worry there is some interference between packages, I have installed following markdown related plugins:
 - `hnw.vscode-auto-open-markdown-preview`, `jrieken.md-navigate`,`shd101wyy.markdown-preview-enhanced`, `ms-vscode.theme-markdownkit`, `AlanWalk.markdown-toc`, `goessner.mdmath`, 

Also I worry that maybe keyboard shortcuts does not work properly in ubuntu (maybe interfere with default ubuntu shortcuts ?).

**Comment by ProkopHapala** [comment]
Aha, sorry it is just that `Right Ctrl+Right Shift+.` works but `Left Ctrl+Left Shift+.` does not.

I was searching how to activate the preview somhow from menu (instead of keyboard shortcut but I did not found anything)

**Comment by psukys** [comment]
Might be that shortcuts are used by several packages and are overriden by later ones.
VSCode recently released a shortcut suggestions for <kbd>Ctrl</kbd> + <kbd>LShift</kbd> + <kbd>P</kbd> command listings:

1. Does `markdown+math` show its bound shortcut?
2. If selecting `markdown+math` from that drop-down list, does it work?

**Comment by goessner** [comment]
`mdmath` as of release 2.0 reuses vscode's native markdown preview. So vscode's preview button should work as expected.

In prior versions the key command <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>.</kbd> was required for that.

Thanks
