### ISSUE TITLE
preview does not render math

### ISSUE THREAD

**Issue by 777Arch** [goessner/mdmath#28]
Hi, 

After installed the extension, I press the preview button upper right the window, but no math rendered.
![image](https://user-images.githubusercontent.com/7379015/29256591-14e6be62-80de-11e7-9439-620afd66d525.png)

![image](https://user-images.githubusercontent.com/7379015/29256608-3bfeba2c-80de-11e7-80f2-4576a9b2957c.png)

On the other hand, when I enter the key combination 'Ctrl + Shift + .'，math is correctly rendered.

Is there any different between them? 

Another issue is, I want to change the default markdown render style by using extension [markdown-preview-github-styles](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles). I don't known how to use "markdown-preview-github-styles" and "Markdown+Math" both. Is there any suggestion?

**Comment by goessner** [comment]
`mdmath` as of release 2.0 reuses vscode's native markdown preview. So the preview button should work as expected.

In prior versions the key command `Ctrl + Shift + .` was required for that.

Thanks
