### ISSUE TITLE
Clip Markdown+Math to HTML command fails

### ISSUE THREAD

**Issue by mihaitodor** [goessner/mdmath#29]
### Summary

When pressing <kbd>Ctrl+K .</kbd> or running the Clip Markdown+Math to HTML, I encounter an error saying "vscode's markdown-it instance inaccessible!" if the preview window hasn't been opened.

### Expected behavior

Copy the generated HTML to clipboard.

### Actual behavior

Getting an error saying "vscode's markdown-it instance inaccessible!"

### Steps to reproduce

1. Open VSCode
2. Open an `.md` file with only `$$\lambda$$` in it
3. Press <kbd>Ctrl+K .</kbd>
4. See error message

### Code example

N/A

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: OSX
       VSCode version: 1.15.1
Markdown+Math version: 2.0.2
```

**Comment by goessner** [comment]
Hmm ... in fact you need to have opened the preview window once here. So I changed the `error` to `info` saying ...

`Corresponding markdown preview document needs to be opened at least once!`

Thanks

**Comment by mihaitodor** [comment]
That is a much more informative message, thank you! :)
