### ISSUE TITLE
Broken display math after code block

### ISSUE THREAD

**Issue by LittleHelicase** [goessner/mdmath#3]
When I create a block of "display math" after a code block the html code for the katex formular gets into the code block.

    ```
    code
    ```
   
    $$a = b$$

results in this.

![image](https://cloud.githubusercontent.com/assets/5698911/21365709/c31c5084-c6f6-11e6-89f1-63e5f4ede2a0.png)

If I put any character between the code block and the display math block it works fine.

**Comment by goessner** [comment]
Need to have a deeper look into that .. thanks.

**Comment by goessner** [comment]
code block bug removed ... thanks.
