### ISSUE TITLE
Clip Markdown+Math to HTML or Ctrl+K . does nothing

### ISSUE THREAD

**Issue by jimaldon** [goessner/mdmath#30]
### Summary

I don't get any error message. There's nothing new copie dto the clipboard either.

### Expected behavior

HTML copied to clipboard

### Actual behavior

No response

### Steps to reproduce

1. md file open
2. open preview
3. Ctrl+K . OR selecting command from F1 menu

**Comment by goessner** [comment]
Please try for copying to the clipboard:

*  You need to have the markdown source window activated here (not the preview window!).
  * The markdown preview window has to be opened once for this in order to function properly.

I this does not help, please tell me.

Thanks
