### ISSUE TITLE
Math markup in a code block doesn't render

### ISSUE THREAD

**Issue by robodasha** [goessner/mdmath#31]
### Summary

Math markup in a code block doesn't render. For example:

![screen shot 2017-09-02 at 17 42 51](https://user-images.githubusercontent.com/1456945/29998974-2ecc8f28-9006-11e7-9c0f-37a5b9dffdf3.png)

As you can see, the math formula in a blockquote renders correctly, but the formula in the code block doesn't. I also tried escaping the dollar symbols:

![screen shot 2017-09-02 at 17 44 20](https://user-images.githubusercontent.com/1456945/29998987-6113f8fe-9006-11e7-978d-90d764e78c7e.png)

Finally, I tried marking the code block using backticks rather than spaces.

Without escaping dollar symbols:

![screen shot 2017-09-02 at 17 50 51](https://user-images.githubusercontent.com/1456945/29999019-58dbe7c2-9007-11e7-8a6f-e903ea7c184b.png)

With escaping:

![screen shot 2017-09-02 at 17 51 07](https://user-images.githubusercontent.com/1456945/29999014-547b4088-9007-11e7-8ebd-858ec919a49c.png)

### Expected behavior

Math markup in a code block will render the math formula correctly.

### Actual behavior

The formula doesn't render.

### Steps to reproduce

1. Open VSCode
2. Start a code block, either using spaces or backticks
3. Insert a math formula inside of the code block
4. Open preview

### Code example

```md
Repeat: {
    w := w - \$\alpha\frac{\partial J(w, b)}{\partial w}\$
    b := b - \$\alpha\frac{\partial J(w, b)}{\partial b}\$
}
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: MacOS Sierra 10.12.6
       VSCode version: 1.15.1
Markdown+Math version: 2.0.3
```

**Comment by goessner** [comment]
@robodasha:

In fact this is not backward compatible behavior.  Math markup in code blocks is now shown - as expected - as markup. This is consistent with surrounding markdown, but - sorry -in contrast to `mdmath` versions prior to 2.0.

I am updating the FAQ's accordingly.

Please - as a workaround - split your code sections and insert your formula comments between them.

Sorry again for the breaking change.

Thanks

**Comment by robodasha** [comment]
Thanks for the response, I'll keep that in mind. It's a shame it doesn't work anymore, but I understand the choice. 

Thank you creating such an awesome plugin!
