### ISSUE TITLE
Support line break in ```math```

### ISSUE THREAD

**Issue by colinfang** [goessner/mdmath#32]
Markdown+Math v2.0.3

Current GitLab flavored latex display mode doesn't work with line breaks

E.g.

### Works

```math
\begin{aligned}   a&=b+c \\   d+e&=f \end{aligned}
```

### Doesn't work

```math
\begin{aligned}
   a&=b+c \\ 
   d+e&=f
\end{aligned}
```

However, the latex looks pretty ugly without line breaks.

Is it hard to add line break support?

**Comment by goessner** [comment]
I am able to reproduce this ...
... so I need to have a deeper look into this.

I will come back to here .. may need some time for that.

Thanks

**Comment by zhanglix** [comment]
@goessner 
I think the problem relates to the regex in 

https://github.com/goessner/markdown-it-texmath/blob/master/texmath.js
```js
rex: /`{3}math\s+?(.+?)\s+?`{3}/gmy,
```
"(.+?)" will not math line terminators. Maybe a quick fix is replace it with "((?:.|\s)+?)"
```js
rex: /`{3}math\s+?((?:.|\s)+?)\s+?`{3}/
```
It works for me now 😆

**Comment by goessner** [comment]
@zhanglix 
In fact I suspected the 'newline' bug with `markdown-it` rules. So I didn't even had a look at thoses regex's.

In the end I replaced the `(.+?)` with '([^`]+?)' which is a bit more performant than your proposal. Both replacements are working like a charme.

Thanks for setting me on the right track.  

btw: We can use those `backticks` inside of TeX by `\backprime`.
