### ISSUE TITLE
Can not work without Internet

### ISSUE THREAD

**Issue by ataghan** [goessner/mdmath#34]
### Summary

... When not connected to the Internet, the plugin is not working.

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: Window7
       VSCode version: 1.15.1
Markdown+Math version: v2.0.3

**Comment by goessner** [comment]
Working offline with `mdmath` is a must .. I agree .. simply was not aware of this.

So I changed the `CDN`-located CSS urls to local files. Now `mdmath` works offline starting from version 2.0.5

Thanks
