### ISSUE TITLE
'Clip Markdown+Math to HTML' command does not work when plugin is installed from inside VSCode

### ISSUE THREAD

**Issue by DERAlfons** [goessner/mdmath#36]
### Summary

The `Clip Markdown+Math to HTML` command does not work for me.
It also never did work for me, but before version 2.0 there was another command, which put out the generated html to a new vscode window.

### Expected behavior

When i run the command `Clip Markdown+Math to HTML` (or press `Ctrl+K .`), the generated html code for my markdown document should be copied to my clipboard and a message should appear, which tells me that that happened.

### Actual behavior

When i run the command `Clip Markdown+Math to HTML` (or press `Ctrl+K .`) (after i generated the html code for my document using the `Open Preview` command and while having the tab with the markdown code active), nothing is copied to my clipboard (my clipboard contains the same thing it contained before running the command) and no message appears.

### Environment

```text
     Operating system: Ubuntu 16.04
       VSCode version: Version 1.17.0
                       Commit be377c0faf7574a59f84940f593a6849f12e4de7
                       Date 2017-10-04T23:33:45.303Z
                       Shell 1.7.7
                       Renderer 58.0.3029.110
                       Node 7.9.0
                       Architecture x64
Markdown+Math version: 2.0.7
```

**Comment by DERAlfons** [comment]
I looked into the issue some more and found out, that the command works when i install the plugin from the command line, but reproduceably does not work when i install the plugin  from inside of VSCode.

What could be causing this?

**Comment by goessner** [comment]
Hello,

I cannot verify this effect with windows 10. But your last observation is really interesting. Nevertheless I have no clue, looking at the javascript code, which code fraction should be responsible here.

So -- help requested -- can someone else confirm this bug with ubuntu OS ?

Please test with both installation cases the existence of all `node_modules`:

![grafik](https://user-images.githubusercontent.com/4902746/31791999-d61eb6d2-b51a-11e7-88f2-78fae8a42107.png)

thanks ...

**Comment by DERAlfons** [comment]
I looked for the `node_modules` and here is what I found:

When installing from within VSCode, all required `node_modules` are there.

When installing from the command line with `npm install`, all required `node_modules` are there, and a lot more, 258 in total:
[pastebin](https://pastebin.com/z44TB7DD)

Here is also the output of `npm install`:
[pastebin](https://pastebin.com/9vWKqGZk)

It seems like the additional module `vscode` and its dependencies are being installed.

**Comment by goessner** [comment]
obviously there is missing something ...
.. can you do me a favor and modify your `mdmath/extension.js` file according to ..
![grafik](https://user-images.githubusercontent.com/4902746/31861225-bf4bc2ae-b729-11e7-9acf-53609cc67281.png)
.. and observe, what happens .. ?

thanks

**Comment by LCAR979** [comment]
@goessner  #44 poster here, and let me know if I can help. I see you code pasted is just same with my local version(mdmath 2.1.0)

**Comment by goessner** [comment]
It works now ...

https://github.com/sindresorhus/clipboardy/issues/36#issue

thanks
