### ISSUE TITLE
link addresses're not converted with relative positions.

### ISSUE THREAD

**Issue by hoyori** [goessner/mdmath#37]
### Summary
when I input `[Legendre's formula](legendre_formula.html)`, it is converted into `<a` `href="file:///d:/markdown/legendre_formula.html">` ...
also image tag too.
...

### Expected behavior
it must be converted into `<a href="legendre_formula.html">`
...

```text
     Operating system: windows 10
       VSCode version: 1.17.2
Markdown+Math version: 2.0.7
```

**Comment by goessner** [comment]
.. this issue is not related to math formulas and `mdmath`. Please raise this issue directly to

[vscode](https://github.com/Microsoft/vscode)
