### ISSUE TITLE
Feature: Inject something to vscode so that highlighter supports dollars

### ISSUE THREAD

**Issue by Ciantic** [goessner/mdmath#38]
I found this:

https://github.com/Microsoft/vscode/issues/27865

Here is the example:

https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example

Where someone mentions it's possible to "extend the builtin markdown grammar", I think this plugin should do it.

To me this is really difficult to read:

![image](https://user-images.githubusercontent.com/64731/32627459-28ef72f8-c59b-11e7-850e-43111d767701.png)

Or consider this:

![image](https://user-images.githubusercontent.com/64731/32627479-3ba71572-c59b-11e7-978d-19c63ba01f76.png)

The built-in highlighter is not good for math.

**Comment by goessner** [comment]
Thanks for the links ... I will have a closer look into this ...

**Comment by goessner** [comment]
Experimental implementation now available with version 2.1
