### ISSUE TITLE
Not supporting escaped underscore

### ISSUE THREAD

**Issue by earthengine** [goessner/mdmath#39]
### Summary

Cannot show escaped underscore

### Expected behavior

When use code
```
\_
```

it should display as

```
_
```
### Actual behavior

It displayed as

```
\_
```

**Comment by goessner** [comment]
.. Sorry .. misinterpreted your issue.

Inside of a code section the behavior you are commenting can be verified. But the effect is still there when you deactivate `mdmath` plugin.

So please raise this issue at `vscode`.

Thanks

**Comment by earthengine** [comment]
No...

What I am saying is,

when you write math specific code

$$
\\_
$$

in preview you still get 

\\_

As specified in <https://khan.github.io/KaTeX/function-support.html#symbols> it should shows

\_


Because neither this or 
```
\textunderscore
```
is supported, there is no way to have a underscore in math context.

**Comment by goessner** [comment]
Verified ... in fact it is a [bug](https://github.com/goessner/markdown-it-texmath/issues/4) with `markdown-it-texmath` ...

It will be fixed with next release.

Thanks
