### ISSUE TITLE
Support existing markdown preview options of vscode

### ISSUE THREAD

**Issue by spion** [goessner/mdmath#4]
Would be nice to support existing options, including "markdown.previewFrontMatter", "markdown.styles", "markdown.preview.fontSize" and "markdown.preview.fontFamily"

Another thing that would be great are configurable inline/display math separators.

**Comment by Immortalin** [comment]
It would also be nice if math don't require a preview pane à la overleaf.

**Comment by goessner** [comment]
@spion: I agree regarding configuration options with styles and frontmatter. Configurable Math separators are not so easy, as variables are not possible in regular expressions. One solution would be to export the regexp's into the configuration file also and let them customize by users.

@immortalin: I also agree here and see advantages in identical behaviour to VSCode's native preview window.

I am currently focused at math stuff, so these aspects have to wait a while for implementing.

Thanks
