### ISSUE TITLE
Qiita delimiters

### ISSUE THREAD

**Issue by hsk** [goessner/mdmath#40]
I use gitlab mode now.

"mdmath.delimiters": "gitlab"

I hope [Qiita](https://qiita.com) markdown delimiters setting.

"mdmath.delimiters": "qiita"

inline $...$
display ```math ... ```

or generalize setting

"mdmath.delimiters": {
inline:["$","$"],
display:["```math","```"]
}

**Comment by goessner** [comment]
.. will have a look into custom delimiters soon ..

thanks

**Comment by RoyiAvital** [comment]
That would be amazing to have User Defined Delimiters.

First step would be allowing `$ ... $`.  
Namely having space after / before the `$` delimiter.  
It works for Display Math (`$$ ... $$` will work) yet the limitation on Inline Math broke many of my existing MarkDown Documents.

Thank You.

**Comment by goessner** [comment]
Decided against user defined delimiters due to low user request rate.

Best way would be to implement it by yourself into [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) and do a pull request.
