### ISSUE TITLE
Stopped working on Windows 10 on VSCode 1.21

### ISSUE THREAD

**Issue by munael** [goessner/mdmath#42]
### Summary
Documents with math display irregular behavior rendering the source code itself followed by the math in non-math font.

### Expected behavior
Math renders.

### Actual behavior
Renders math source code in the same font as surrounding text followed by a non-math font rendering of the math.

### Steps to reproduce

1. Preview example code in VSCode 1.21 Insiders on Windows 10.

### Code example

```md
$$
\begin{aligned}
    S &\le 25 \\
    V &\ge 240
\end{aligned}
$$

$|-$
```

![image](https://user-images.githubusercontent.com/5769148/36785207-ba96aeb0-1c8a-11e8-8624-638eb61c4baf.png)

### Environment

```text
     Operating system: Windows 10 Creators Update
       VSCode version: 1.21
Markdown+Math version: 2.1.0
```

**Comment by goessner** [comment]
Yes ... verified ... thanks @

**Comment by goessner** [comment]
Once issue https://github.com/Microsoft/vscode/issues/45007 is resolved, `mdmath` should work as expected with Windows 10.

**Comment by goessner** [comment]
Just tested with VSCode 1.22.0 insiders build. See https://github.com/Microsoft/vscode/issues/45007

It is working now again. So we are waiting for Release VSCode 1.21.1.
