### ISSUE TITLE
[Enhancement] Use MathJax or Update KaTeX Version

### ISSUE THREAD

**Issue by ghost** [goessner/mdmath#43]
Hi, 

The KaTeX using now is @0.8.3, and does not support various commands. Would you like to use use more mature packages like MathJax, or if you don't bother to change code, update version of KaTeX to the latest? Now even `\boldsymbol` is not usable, and it causes problems when I'm typesetting vectors, etc.

Many thanks for your work!

**Comment by goessner** [comment]
I am just waiting for another big issue being resolved ...

https://github.com/goessner/mdmath/issues/42

... before updating `mdmath` also using KaTeX @0.9.0.

I know of `\boldsymbol`, but what is the issue with vectors ?

thanks
