### ISSUE TITLE
VS Code complains 'Html copying to clipboard failed' when run the command

### ISSUE THREAD

**Issue by LCAR979** [goessner/mdmath#44]
### Summary
I wrote a markdown file with lots of latex-sytax equations. But when I use the command palette to run `Markdown:clip Markdown+Math to HTML`, the VS Code info window pops up and shows 'Html copying to clipboard failed'
I found someone reported this issue before and it is suggested to open the preview window once then run that command. And I actually opened the markdown source window and the preview window at left and right windows of VS Code seperately, so I think maybe something other is wrong with my environments,
...

### Expected behavior
Run the clip command and HTML content is clipped to clipboard.
...

### Actual behavior
VS Code info window pops up saying `Html copying to clipboard failed`
...

### Steps to reproduce

1. First step: Create a new markdown file, write just `$\lambda$`
2. Second step: Press Ctrl+P to call out the command palette window
3. Third step: Run `Markdown:clip Markdown+Math to HTML`

### Code example

```md
$\lambda$  

Cannot clip to clipboard 
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: _Ubuntu 16.04 LTS_
       VSCode version: _ 1.20.1_
Markdown+Math version: 2.1.0
```

**Comment by goessner** [comment]
Thanks for verifying this issue with Ubuntu. The first one was raised here.

https://github.com/goessner/mdmath/issues/36

We use [clipboardy](https://github.com/sindresorhus/clipboardy) for accessing the system clipboard, so I will ask there if it really has issues with Ubuntu.

Thanks

**Comment by goessner** [comment]
it works now ..

thanks
