### ISSUE TITLE
Can mdmath support 'align' environment?

### ISSUE THREAD

**Issue by MagShadow** [goessner/mdmath#45]
Sometimes i want to type in more-than-one-line formulas, but it seems that mdmath doesn't support that.

```markdown

$$ \begin{align} S' =((x_1+x_2)(1+\epsilon_1)+x_3)(1+\epsilon_2)+...\end{align}$$

```

However, it doesn't work and show such log: ParseError: KaTeX parse error: No such environment: align at position 7: \begin{̲a̲l̲i̲g̲n̲}̲ S' =

**Comment by goessner** [comment]
KaTeX does not support `\begin{align}` at current, but `\begin{aligned}`. So
```
$$ \begin{aligned} S' =((x_1+x_2)(1+\epsilon_1)+x_3)(1+\epsilon_2)+...\end{aligned}$$
```
should work.

Look here, what KaTEX supports

https://khan.github.io/KaTeX/function-support.html

**Comment by RoyiAvital** [comment]
Would you reconsider adding support for MathJaX in addition to KaTeX?

Thank You.
