### ISSUE TITLE
`\newline` does not work.

### ISSUE THREAD

**Issue by LinkClinton** [goessner/mdmath#46]
### Summary

`\newline` does not work and `\\` is ok. ("mdmath.delimiters": "dollars")

### Expected behavior

`\newline` is same as `\\`

### Actual behavior

`\newline` => \newline

### Steps to reproduce

See code example.

### Code example

```md
$$
 A = \left[
    \begin{matrix}
    1 & 0 & 0 & 0 \newline
    0 & 0.5 & 0 & 0 \newline
    0 & 0 & 0.5 & 0 \newline
    1 & 1 & 1 & 1
    \end{matrix}
    \right]
$$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system:  Windows 10 16299.248
       VSCode version:  1.22.0-insider
Markdown+Math version:  2.1.0
```

**Comment by RoyiAvital** [comment]
This is just part of KaTeX being limited in features.

We really need something with MathJaX in VS Code.

**Comment by goessner** [comment]
@LinkClinton: This is an issue with https://github.com/Khan/KaTeX, as you correctly identified it. So please raise an issue there, after verifying by testing with
https://khan.github.io/KaTeX/
So please don't blame `mdmath` for not parsing math correctly.

@RoyiAvital: There are already MathJax based solutions with VSCode available. Use those. I don't have time for integrating additional math parsers, where users will blame me then for their 10 times slower speed. 

Please note, that current Version of VS Code 1.21.1 works with mdmath. So you simply need to update and don't need insider version anymore.

thanks

**Comment by RoyiAvital** [comment]
@goessner , Do you know extension which integrates with VS Code MD Preview with MathJaX?
Namely only parses `$ ... $` and `$$ ... $$`?

Regarding MathJaX. 
For most cases the speed difference isn't noticeable (I had 30 pages of work in StackEdit v4 [Used MAthJaX] which online application and never had any speed issue).
On top of that you can let the user make the choice (KaTeX being the default).

But you know, for a starter, could you just let `$ ... $` be parsed as In Line Math without enforcing the "No Spaces" policy?
It will assist with compatibility for people with many already written MarkDown documents.

Thank You.

**Comment by goessner** [comment]
I commented regarding this over here ... 

https://github.com/goessner/mdmath/issues/22#issuecomment-373712700
