### ISSUE TITLE
"cilpToHtml" uncorrect picture url  

### ISSUE THREAD

**Issue by ianchen-tw** [goessner/mdmath#48]
### Summary
Need to manually remove the "vscode-workspace-resource" to load picture successfully. 
...

### Expected behavior

mark down picture : 

`![pic1-1: Node explored under different searching method](./pic/cmp_eng.png)
`

expected html : 
`<p data-line="36" class="code-line"><img src="/Users/chenyian/Desktop/projects/intro2AI/hw1/pic/cmp_eng.png" alt="pic1-1: Node explored under different searching method"></p>`

...

### Actual behavior
( note the prefix if src "vscode-workspace-resource")

`<img src="vscode-workspace-resource:/Users/chenyian/Desktop/projects/intro2AI/hw1/pic/cmp_eng.png" alt="pic1-1: Node explored under different searching method">`
...

### Steps to reproduce

1. First step
 write a resource syntax in markdown
2. Second step
use command `Makrdown : Clip Makrdown+Math to HTML`

3. Third step

open the html file in chrome

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: OSX10.13.3
       VSCode version: 1.21.1
     chrome version: Version 67.0.3371.0 (Official Build) dev (64-bit)

Markdown+Math version: 2.2.1
```

**Comment by goessner** [comment]
Yes, I can reproduce this. Must have come in with a newer version of vscode.

I will  investigate this some more in depth and presumably fix it with the next version.

Thanks
