### ISSUE TITLE
Unable to open files...

### ISSUE THREAD

**Issue by sequencer** [goessner/mdmath#5]
I'll have a important exam tomorrow...
And my note can only be opened by mdmath...
after this afternoon's update...
I can't open my all notes
for example
[数学答案订正.txt](https://github.com/goessner/mdmath/files/670447/default.txt)
it's a Chinese note, wrote in UTF-8.
It says
`Unable to open 'Preview: 数学答案订正.md': KaTeX parse error: Expected 'EOF', got '重' at position 1: 重̲根对应.`
Plz save me...

**Comment by goessner** [comment]
Not sure what you mean with 'this afternoon' ... I only updated the readme today ...

It seems to be a bug and I have to do a closer look into it. But I managed to get it work by surrounding all inline formulas with blanks.


![grafik](https://cloud.githubusercontent.com/assets/4902746/21453106/52c8be36-c90c-11e6-8c7b-fb8f15ce9e4a.png)

Hope that helps .. thanks

**Comment by sequencer** [comment]
Thank you so much.
I think it's the problem of ktex?
I have downgraded to 0.8 it works well. 
Thanks!

**Comment by goessner** [comment]
So you should raise an issue also [there](https://github.com/Khan/KaTeX)  .. perhaps with linking to here .. please.

Thanks
