### ISSUE TITLE
Want to config the image path when Clip Markdown+Math to HTML

### ISSUE THREAD

**Issue by taoluo** [goessner/mdmath#54]
I have some image links in my markdown file, and they are rended properly in preview mode. But when it comes to Clip the HTML, the src of image turns out to be `src="vscode-resource:/absolute/path/to/image.png.` and the image doesn't appear when opened in browser.

I think It's good to have some setting to config the image path as relative path.

**Comment by goessner** [comment]
Thanks for your input.

I will come later back to that.

**Comment by goessner** [comment]
The `vscode-resource:` string is now removed from the `src` path. So images should work properly with that.

The pathes are still absolute. But is would be hard and often incorrect to substitute absolute  pathes with relative ones in a html text file.

So to adapt pathes simply do a `search and replace` in your html source.

**Comment by upupming** [comment]
I encountered the image path problem, too.

I think we could add a configuration such as:

```json
"mdmath.absoluteImgPath": false
```

In this way, we can choose whether to use an absolute path or not. I prefer to use relative path because I want to generate an HTML file and host it on something like GitHub Pages. Is it possible?
