### ISSUE TITLE
View inline formulas in HTML blocks

### ISSUE THREAD

**Issue by varkor** [goessner/mdmath#56]
I have something like the following:
```markdown
<aside class="highlight">The formula is $x + y$.</aside>
```
Right now, `x + y` does not format as an inline formula. Is there any way to do this?

**Comment by goessner** [comment]
`mdmath` relies on [https://github.com/markdown-it/markdown-it](https://github.com/markdown-it/markdown-it) parsing the document.

So, as 

```html
<div>The formula is $x + y$.</div>
```

doesn't give the wanted result. It's the same reason as even 

```html
<div>The formula is *x + y*.</div>
```

doesn't render the markdown properly.

So there is unfortunately no way for `mdmath` inspecting and processing the content of those block elements.
