### ISSUE TITLE
Export doesn't work for me

### ISSUE THREAD

**Issue by simplex3** [goessner/mdmath#57]
### Summary
Allways get error messages when trying to export a file (to pdf, png,...) in vscode.
...

### Expected behavior

Convert md to png, pdf,...

### Actual behavior

error messages 

### Steps to reproduce
The normal way... Rightclick...Export...

### Code example

```
>$$\sum_{k=1}^{n}\frac{1}{k}=\infty$$
>$$a²=\sqrt{c}$$


```

### Related links

![bildschirmfoto vom 2018-09-02 10-59-58](https://user-images.githubusercontent.com/203988/44954245-660d9780-ae9f-11e8-8366-9b1b754da375.png)

### Environment

```text
     Operating system: Linux Mint 19
       VSCode version: 1.2.6
Markdown+Math version: latest from Marketplace
Latest Chrome is installed
```

**Comment by goessner** [comment]
You cannot export directly to `*.pdf` from within vscode.

So please ...

* Launch *VS Code*, create or open a markdown file (`.md`).
* Open a preview window.
* Typeset in your markdown source window and see the preview window live updating.
* Give focus to the source code window.
* Press <kbd>Ctrl+K .</kbd> or run the command `Clip Markdown+Math to HTML` to copy the 
  corresponding HTML source to the underlying systems clipboard.
* Copy the  HTML source to a separate file.
* Open that file by any browser.
* Print from browser to `*.pdf`

Hope that helps.
