### ISSUE TITLE
Adding intellisense or autocomplete to Markdown+Math might be a good idea.

### ISSUE THREAD

**Issue by xiezhuojin** [goessner/mdmath#59]
### Summary
I am trying to use vs-code as my daily use markdown editor, but I find out there are no markdown extensions that support math syntax. There is an extension called LaTeX Workshop that supports autocomplete, but only in  .tex files. I really hope there is a way to use autocomplete.

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Code example

```md
Some markdown code ...

... with issues.
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: ___
       VSCode version: ___
Markdown+Math version: ___
```

**Comment by goessner** [comment]
There are already Markdown intellisense supporting extensions out there, which you might want to install in parallel. I would like to keep mdmath as lean and as performant as possible at current.

Sorry & thanks
