### ISSUE TITLE
Markdown preview is clipped when using VSC window zoom feature ["Cmd" + "+"]

### ISSUE THREAD

**Issue by krzyzak00** [goessner/mdmath#6]
I'm not sure if this is an extension issue or VSC bug but this is how it looks:

<img width="1440" alt="clipping_issue" src="https://cloud.githubusercontent.com/assets/2048483/21643978/702e2b72-d28b-11e6-99c0-b300228f08ff.png">

Retina Macbook, OS X El Capitan, Visual Studio Code 1.8.1, Markdown+Math 1.1.0

**Comment by goessner** [comment]
It's a known issue with vscode's webview ...
https://github.com/Microsoft/vscode/issues/15425
.. I also hope for a fix in near future ...

Thanks
