### ISSUE TITLE
Is the environment align* supported?

### ISSUE THREAD

**Issue by trongr** [goessner/mdmath#60]
### Summary

I'm trying to use \begin{align*}...\end{align*} but it doesn't seem to be working.

### Expected behavior

This  snippet

```
\begin{align*}
1 &= \det I \\
  &= \det(Q^{T} Q) \\
\end{align*}
```

without bounding \\[ ... \\] should render as correct math.

### Actual behavior

It's rendering as plain text in Markdown preview.

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: MacOS 10.12
       VSCode version: 1.27.2
     Markdown+Math version: 2.3.4
```

**Comment by goessner** [comment]
use 
```
\begin{aligned}
   a&=b+c \\
   d+e&=f
\end{aligned}
```
instead.

See [reference](https://khan.github.io/KaTeX/docs/supported.html) what's supported.

**Comment by makslevental** [comment]
doesn't work for me: begin{aligned} middle of the right pane

![image](https://user-images.githubusercontent.com/5657668/74965255-e51fc400-53e2-11ea-8c27-2228c45e13c9.png)
