### ISSUE TITLE
Incorrect display of square root in fraction

### ISSUE THREAD

**Issue by frankcai** [goessner/mdmath#61]
After typing the following:

$$frac{\sqrt{115}}{35}$$

I get this:

![image](https://user-images.githubusercontent.com/1742804/46699349-cbc90e00-cc19-11e8-9cb4-b592fc8995e1.png)

Shouldn't this be displayed as a correct fraction?

### Environment

```text
     Operating system: Win 10
       VSCode version: 1.29.0-insider
Markdown+Math version: 2.3.4
```

**Comment by notZaki** [comment]
Try `\frac` instead of `frac`.

**Comment by frankcai** [comment]
Thanks. Missed that somehow.
