### ISSUE TITLE
Macro's from settings not working

### ISSUE THREAD

**Issue by recmo** [goessner/mdmath#63]
### Summary

The macro example from the Readme is not working.

As mentioned in [comment](https://github.com/goessner/mdmath/issues/51#issuecomment-423863994) on a related issue, macro support is critical for any serious mathematical work.

### Expected behavior

Preview without errors.

### Actual behavior

Red symbols `\RR` and `\vek`.

### Steps to reproduce

1. Add example config to settings.json
2. Restart VS Code just in case
3. Open new workspace
4. Create new file `Test.md`
5. Paste example markdown.
3. Press `⌘K V`

### Code example

My settings.json:
```json
{
    "breadcrumbs.enabled": true,
    "editor.renderWhitespace": "all",
    "editor.rulers": [
        80,
        120
    ],
    "window.zoomLevel": 0,
    "mdmath.macros": {
        "type": "object",
        "default": {
            "\\RR": "\\mathbb{R}",
            "\\vek": "{\\begin{pmatrix}#1\\\\#2\\end{pmatrix}}"
        },
        "description": "TeX macros definition."
    }
}
```

Test.md:
```md
Vectors in $\RR^2$ have a shape of

$$\vek{x}{y}$$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: MacOS 10.14.1 (18B75)
       VSCode version: Version 1.29.1 (1.29.1)
Markdown+Math version: 2.3.6
```

**Comment by recmo** [comment]
Aside: My markdown files have `\newcommand` macros at the top. This is currently not supported by Katex. But when converted to `\gdef` macros they work. I prefer this over having my macros in settings, as it makes the files self-contained.

Edit: I've since learned that this is a difference between Mathjax (which I use) and Katex (which mdmath uses). Mathjax has more continuity between math blocks. Katex only retains global definitions: [docs](https://katex.org/docs/supported.html#macros). Katex seems more strict, but reasonable.

**Comment by goessner** [comment]
@Recmo: In the current readme there was mistakenly the package.json format listed:

```json
    "mdmath.macros": {
        "type": "object",
        "default": {
            "\\RR": "\\mathbb{R}",
            "\\vek": "{\\begin{pmatrix}#1\\\\#2\\end{pmatrix}}"
        },
        "description": "TeX macros definition."
    }
```
In user settings you merely have to add:

```json
 "mdmath.macros":  {
     "\\RR": "\\mathbb{R}",
     "\\vek": "{\\begin{pmatrix}#1\\\\#2\\end{pmatrix}}"
}
```

Readme was updated ...

thanks

**Comment by rjmigliori** [comment]
I can't get this to work. Identical behavior to OP. On windows 10 Enterprise.
