### ISSUE TITLE
Macro's not reset

### ISSUE THREAD

**Issue by recmo** [goessner/mdmath#64]
### Summary

Once defined, macros are not forgotten even when the definition is removed.

### Expected behavior

Macro's should be unset when their definition is removed. Usage of undefined macro should result in an error.

### Actual behavior

The last definition before removing is used.

### Steps to reproduce

1. Create a document with the example code below.
2. Open preview.
3. Remove the first math block.

### Code example

```md
$$
\gdef\test{TEST}
$$

$$
\test
$$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: MacOS 10.14.1 (18B75)
       VSCode version: Version 1.29.1 (1.29.1)
Markdown+Math version: 2.3.6
```

**Comment by goessner** [comment]
Resetting / removing macros should work now simply by resetting / removing `mdmath.macros` from user settings.

Maybe restarting vscode might be necessary.

Thanks
