### ISSUE TITLE
AsciiMath support

### ISSUE THREAD

**Issue by niclasmattsson** [goessner/mdmath#67]
For those of us who aren't already proficient with LaTeX, [AsciiMath](http://asciimath.org/) is a much easier alternative to learn. It may be more limited than LaTeX but its (relative) simplicity and readability makes it a natural fit with Markdown. It would be great if mdmath supported equation entry with AsciiMath. Have a look at this [AsciiMath to TeX library](https://github.com/christianp/asciimath2tex) - you may find that all the heavy lifting is already done.

**Comment by goessner** [comment]
I remember having had a closer look at AsciiMath in the past and found, it really has its charme.

A killer argument, not to use it for my personal math, was the missing tilde akcent ... IIRC. But this is only just a personal requirement - from the sum of which I developed mdmath.

Another more problematic argument would be the necessary two stage parsing process:

1.) AsciiMath => TexMath
2.) TexMath => HTML/SVG/whatever

which won't be as performant as step 2) alone.

But feel free to fork mdmath and add AsciiMath functionality by yourself.

Thanks

**Comment by sebi5361** [comment]
+1 for this feature!
