### ISSUE TITLE
\gdef and \global\def do not always work

### ISSUE THREAD

**Issue by kwhatmough** [goessner/mdmath#70]
### Summary

`\gdef` and `\global\def` only seem to work if one or more global macros are defined in VSCode settings. Otherwise, macros defined using `\gdef` and `\global\def` fail to persist between math blocks.

### Expected behavior

Macros defined using `\gdef` and `\global\def` should always persist between math blocks.

### Actual behavior

If no global macros are defined in `settings.json`, the macros defined in `\gdef` and `\global\def` fail to persist between math blocks. Macro names appear in red in any subsequent math blocks.

### Steps to reproduce

1. Ensure one of the following conditions are met:
    - No `settings.json` exists
    - `settings.json` exists but has no `"mdmath.macros"` key
    - `settings.json` exists and has a `"mdmath.macros"` key, but the value is an empty object.
1. Restart VSCode.
1. Create a `.md` file in VSCode based on the Code Example below.
1. Open the preview and observe that the `\positive` macro is undefined in the second code block and appears in red.

If you add a global macro in settings and restart VSCode, the `\positive` macro will be defined and the red text will change to `negative` text.

### Code example

```md
$$\gdef\positive{\text{negative}}$$

$$\text{Bug detected: }\positive$$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
Operating system: macOS 10.11.5
VSCode version: 1.33.1
Markdown+Math version: 2.3.9
```

**Comment by goessner** [comment]
Hmm ... [KaTeX documentation](https://katex.org/docs/supported.html#macros) is exactly telling us, what you are saying:

`\gdef` and `\global\def` macros will persist between math expressions. 

In fact there is a discrepancy between documentation and behavior.

So I would like to encourage you, to ...
* raise this issue at [`KaTeX`](https://github.com/KaTeX/KaTeX)
* define global macros with VSCode settings

thanks
