### ISSUE TITLE
[Feature-request] External file for macros

### ISSUE THREAD

**Issue by PierreMarchand20** [goessner/mdmath#72]
It would be nice to be able to store all the user-defined in a external file. This will avoid overload the settings with macro definitions.

**Comment by goessner** [comment]
Hmm ... I think this is doable.

Before starting to code I would like to ask ...      
*Are there possibly more than three people interested in that feature*? :) 

thanks

**Comment by danmackinlay** [comment]
This would effectively be a poll of the interested parties for #51  and #70, right?

**Comment by shannonPrice** [comment]
Stop sending me emails thank you

Shannon’s iPhone x 

On Oct 6, 2019, at 5:27 PM, Stefan Goessner <notifications@github.com> wrote:

Hmm ... I think this is doable.

Before starting to code I would like to ask ...
Are there possibly more than three people interested in that feature? :)

thanks

**Comment by danmackinlay** [comment]
@shannonPrice  you are subscribed to this conversation via github. You can either click on the "unsubscribe" or "mute" link in the notification emails that github sends you, or "unfollow" the issue on the github page, but none of the rest of us have any power over your github settings, (and just FYI, replying to the email is spamming this github issue and sending unwanted notifications to everyone else.) Good luck!

**Comment by goessner** [comment]
It should work now as requested with version 2.4.0.

thanks
