### ISSUE TITLE
\dddot does not work

### ISSUE THREAD

**Issue by rkulow** [goessner/mdmath#73]
### Summary
\dddot{a} does not work

### Expected behavior
\dddot{a} should produce a 'a' with three dots above

### Actual behavior
actually \dddot{a} produces a syntax error

### Steps to reproduce
add \dddot{a} to your code

### Code example

```md
\dddot{a}
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: Windows x64 10.0.17763
       VSCode version: 1.33.1
Markdown+Math version: 2.3.9
```

**Comment by yuekai** [comment]
KaTeX does not support this:

[Things that KaTeX does not (yet) support](https://github.com/KaTeX/KaTeX/wiki/Things-that-KaTeX-does-not-(yet)-support)
