### ISSUE TITLE
Support for pandoc-crossref syntax

### ISSUE THREAD

**Issue by masonlr** [goessner/mdmath#74]
### Summary

Support for http://lierdakil.github.io/pandoc-crossref/ syntax would improve the experience for scientific writing.

### Expected behavior

Input such as the following should not break the preview:

```markdown

$$
a + b = c
$$ {#eq:foo}

This is a cross reference to @eq:foo above.

```

### Actual behavior

The input is breaking the preview:

![image](https://user-images.githubusercontent.com/5828176/58648666-1a8afb80-8302-11e9-84d0-a6d0b90e2123.png)

### Steps to reproduce

Create a `test.md` file with the contents:

```markdown
$$
a + b = c
$$ {eq:foo}

This is a cross reference to @eq:foo above.
```

### Code example

See above.

### Related links

* [pandoc-crossref](http://lierdakil.github.io/pandoc-crossref/)

### Environment

```text
     Operating system: macOS
       VSCode version: Version 1.35.0-insider (1.35.0-insider)
Markdown+Math version: 2.3.9
```

**Comment by goessner** [comment]
Yes, this would indeed improve math writing experience. And I also know, that the equation numbering implemented with `mdmath` is a *poor man's solution*.

With `mdmath`'s pragmatic solution, where ...

* `markdown-it`  is a working module inside of vscode ...
* `katex` is a plugin of  `markdown-it` ...

it would be an inacceptable effort to implement cross references between these different layers - at least for me. Maybe it is doable, but it might come with additional performance penalty for sure.

Sorry & thanks
