### ISSUE TITLE
Math symbols are not showing in table in VS Code

### ISSUE THREAD

**Issue by zeckdude** [goessner/mdmath#75]
### Summary

I am using the double dollars signs and it shows up great in actual Github Markdown, but not in the preview pane when used in a table. When the same code is used outside of a table, it works fine.

*Not working in the preview pane*
<img width="1139" alt="Screen Shot 2019-06-02 at 9 47 52 PM" src="https://user-images.githubusercontent.com/947856/58776900-07d22a00-8581-11e9-8d89-2dd9c3ba0038.png">

*Working in Github*
<img width="1362" alt="Screen Shot 2019-06-02 at 9 47 23 PM" src="https://user-images.githubusercontent.com/947856/58776907-10c2fb80-8581-11e9-8699-1bfc6e3efb6c.png">

### Expected behavior

The math symbols render correctly inside a table cell

### Actual behavior

The math symbols don't render and instead show the Latex code.

### Steps to reproduce

1. Create a table
2. Add the following Latex code in a table cell: `$$ 6, -\tfrac{7}{2}, 0, \tfrac{3}{4}, \tfrac{11}{6}, 12 $$`
3. Look at the table in the preview pane

### Code example

```md
| Term | Definition | Example |
|---------------|----------------------------------------|----------------------------------------------------------|
| Rational number | Any number that is either an integer or a fraction  | $$ 6, -\tfrac{7}{2}, 0, \tfrac{3}{4}, \tfrac{11}{6}, 12 $$ |
```

### Related links

* You can see it working in the table at: https://github.com/zeckdude/knowledge-base/blob/master/math.md 

### Environment

```text
     Operating system: Mac OSX
       VSCode version: 1.34.0
Markdown+Math version: 2.3.9
```

**Comment by goessner** [comment]
Unfortunately we cannot use block elements inside of tables with markdown ... [see](https://www.markdownguide.org/extended-syntax/#tables).

This is the reason, why display style (block) equations don't work in tables.

Also see [this issue in `mardown-it-texmath`](https://github.com/goessner/markdown-it-texmath/issues/14) where this issue actually should be directed to.

So - as a workaround - simply change your display math to inline math here. I will put this hint to the FAQ  section.

thanks
