### ISSUE TITLE
Line starting with inline math rendered as display, discarding following contents.

### ISSUE THREAD

**Issue by smdsbz** [goessner/mdmath#76]
### Summary

If a line starts with inline math, followed by some normal texts, the inline math will be rendered as display math, and the texts following the math got discarded.

E.g. for the following paragraph

```markdown
$$r_{max}$$ is unknown ...
```

### Expected behavior

![image](https://user-images.githubusercontent.com/19503270/61759658-92097280-adfb-11e9-8fd3-6d57dc06c8b8.png)

Where the paragraph is left-aligned, and the text `is unknown ...` is displayed.

### Actual behavior

![image](https://user-images.githubusercontent.com/19503270/61759727-bd8c5d00-adfb-11e9-9b49-8732a1bf3a99.png)

Where the paragraph is rendered as a display math, i.e. centered, and the text is discarded.

### Workaround

My guess is that it might be a bug of the parser, thus preceding the math with some blank element, making the inline math not longer the first object of the paragraph will fix the issue. However its better the bug gets fixed.

```markdown
<span></span>$$r_{max}$$ is unknown ...
```

will render correctly

![image](https://user-images.githubusercontent.com/19503270/61759916-65098f80-adfc-11e9-99c6-7efc920514e8.png)

### Environment

```text
Operating system: Windows 10
VSCode version: 1.36.1
Markdown+Math version: 2.3.9
```

**Comment by goessner** [comment]
I do not know, which `delimiters` you are using. If you use the default `dollars` delimiters, then
```
$r_{max}$ is unknown ...
```
is to be used for inline math. But ...

... your proposed workaround is indeed quite interesting :)

In fact, what you are calling a bug, is a feature of `markdown-it`, which `vscode` uses as its markdown renderer - and so inevitably does `mdmath`. 

See [this issue of `markdown-it-texmath`](https://github.com/goessner/markdown-it-texmath/issues/16) for a more indepth discussion.

I need to think a little longer about the potential of your workaround ...

thanks
