### ISSUE TITLE
Codelens math preview

### ISSUE THREAD

**Issue by danmackinlay** [goessner/mdmath#78]
As noted at #69 there are  performance problems with rendering equations in large documents.

The Rstudio approach to avoid this problem is different to the one I proposed in #69.
The have [inline preview](https://twitter.com/rstudiotips/status/964562660351033344?lang=en) in the style of [codelens](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup) and so only ever show one equation at a time, rather than doing an expensive re-render of the whole document.

![inline math preview](https://pbs.twimg.com/media/DWLQQJYVQAAD_cu?format=jpg&name=small)

This is of course, not quite the same thing as the markdown preview itself, but this seems to be the most appropriate project to host such a solution; Also Codelens feels like an VS-idiom, and as such is possibly a better alternative math rendering speedup option for long documents. 

As such, posting the idea here for comment.

**Comment by goessner** [comment]
This is definitely a solution worth to have a deeper look  into in future.

thanks
