### ISSUE TITLE
Arrow Composition is not supported?

### ISSUE THREAD

**Issue by rizary** [goessner/mdmath#79]
Hi,

I want to create this image:
![this image](https://user-images.githubusercontent.com/7221768/66442736-2c29a000-ea66-11e9-9a09-956cff9f396f.png)

and this image:
![image](https://user-images.githubusercontent.com/7221768/66442762-46637e00-ea66-11e9-8135-444ffa930fe9.png)

But I cannot display it. How to do this using mdmath?

**Comment by goessner** [comment]
`mdmath` can only support functions, which are [math functions supported by KaTeX](https://katex.org/docs/supported.html).
