### ISSUE TITLE
Rendering doesn't work on files opened from Windows network paths as \\server\folder\file.md

### ISSUE THREAD

**Issue by stefan-muc** [goessner/mdmath#85]
### Summary
Rendering doesn't work on files opened from Windows network paths as `` \\server\folder\file.md`` 

### Expected behavior
Markdown+Math should render file identically, no matter from which location it's opened

### Actual behavior
Top one: File opened from a drive (can be a mapped network drive too) renders correctly
Bottom one: The exact same file opened from a network path as ``\\server\folder\file.md`` renders weird (seems like formulas are doubled)
![Code_2020-01-13_10-39-04_stripped](https://user-images.githubusercontent.com/544335/72247035-54d8ad00-35f4-11ea-97d0-3351f3f97717.png)

### Steps to reproduce

1. download ``triangle.md`` from this repository
2. put file onto network server (I guess opening from a local share has same effect)
3. display preview

### Code example
[triangle.md](https://github.com/goessner/mdmath/blob/master/triangle.md) from this repository

### Environment

```text
     Operating system: Windows 7 (6.1 Build 7601: Service Pack 1)
       VSCode version: 1.14.1
Markdown+Math version: 2.4.0
```

**Comment by goessner** [comment]
Having a closer look at your screenshot shows, that not only math formulas are broken (should be related to css) but also the surrounding text has different style. As well as the editor file symbols in the upper right corner.

So it should be hardly a `mdmath` issue. Perhaps it's similar to [that issue](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/1720).

Reopen, if there are new insights.

Thanks
