### ISSUE TITLE
Save to HTML eats »=« sign in relative links

### ISSUE THREAD

**Issue by stefan-muc** [goessner/mdmath#86]
### Summary
Markdown+Math Extension offers a HTML export of a markdown file. In this export, the »=« (equal) sign in links is missing, but only for relative links. This sign should also be supported for relative links.

### Expected behavior
All links include the equal sign, no matter of the type

### Actual behavior
Relative links are missing the equal sign, which breaks the link

### Steps to reproduce
Export Code example with Markdown+Math's HTML export command

### Code example
```md
[not working link](docs/myfile.pdf#page=42) gets exported as ``#page42``

[working link](file://///server/path/doc/myfile.pdf#page=42) gets exported as ``#page=42``
```

Result:
```html
<p data-line="0" class="code-line"><a href="docs/myfile.pdf#page42" data-href="docs/myfile.pdf#page42">not working link</a> gets exported as <code>#page42</code></p>
<p data-line="2" class="code-line"><a href="file://///server/path/doc/myfile.pdf#page=42" data-href="file://///server/path/doc/myfile.pdf#page=42">working link</a> gets exported as <code>#page=42</code></p>
```

### Environment
```text
     Operating system: Windows 7 (6.1 Build 7601: Service Pack 1)
       VSCode version: 1.14.1
Markdown+Math version: 2.4.0
```

### Rationale
Why am I doing this? When you set a link to ``myfile.pdf#page=42`` your browser will not just only open ``myfile.pdf`` but also switch to page ``42`` -  which is quite convenient with linking to large pdf documents.

### Related links
* [How to link to a page in a pdf file.](https://www.joomlatools.com/blog/tutorials/how-to-link-to-a-page-in-a-pdf-file)

**Comment by goessner** [comment]
That is clearly reproducable.

So I raised an issue in vscode

#https://github.com/microsoft/vscode/issues/94508

Thanks

**Comment by goessner** [comment]
closed due to ...

#87 https://github.com/microsoft/vscode/pull/94655
