### ISSUE TITLE
Macros don't render (followed README)

### ISSUE THREAD

**Issue by lgtm70b** [goessner/mdmath#87]
<img width="1427" alt="Screen Shot 2020-01-16 at 5 35 56 PM" src="https://user-images.githubusercontent.com/23650385/72574556-b1eb9180-3886-11ea-98e4-a82a361e10bb.png">

Hi, I followed your directions for setting up macros, added directly to the using settings.json using your setup from the README, but it's unfortunately not rendering in the preview.

**Comment by lgtm70b** [comment]
Post-restart VSCode works fine, nevermind.

**Comment by lgtm70b** [comment]
I'm struggling to get other macros to function. Could you advise, or if it's obvious, add some more examples on how you would expand macros that aren't escaped like what's in the README?  I'm trying to port the vim Ultisnips snippets I found from a math student [here](https://castel.dev/post/lecture-notes-1/), after I converted them to regular VSCode snippets with [this npm package](https://github.com/VincentCordobes/convert-snippets). 

I'd like to use this package's macros / math and markdown integration instead of standard VSCode snippets but I'm still having trouble getting my own examples to render. Anything obvious I'm missing?

image and snippets files attached for reference

<img width="1025" alt="Screen Shot 2020-01-17 at 7 55 40 PM" src="https://user-images.githubusercontent.com/23650385/72657692-6effeb80-3964-11ea-8e23-93df4c6ab912.png">

[tex_dot_json.txt](https://github.com/goessner/mdmath/files/4079902/tex_dot_json.txt)
[tex_dot_snippets.txt](https://github.com/goessner/mdmath/files/4079903/tex_dot_snippets.txt)

**Comment by goessner** [comment]
Hmm ... most of the examples in your files do not follow that, what KaTeX supports. See

https://katex.org/docs/supported.html#macros

Simply restrict your macros to theses rules, as `mdmath` relies on KaTeX.
