### ISSUE TITLE
Display mode not working 

### ISSUE THREAD

**Issue by TiansuYu** [goessner/mdmath#88]
I am not sure how this issue could appeared. However, the following code displayed normally inline 
```
$P(A \cup B) = P(A) + P(B)$

$P(H | D)  = \frac{P(D|H) \cdot P(H)}{P(D)}$
```
while not in display mode 
```
$$P(A \cup B) = P(A) + P(B)$$

$$P(H | D)  = \frac{P(D|H) \cdot P(H)}{P(D)}$$
```

**Comment by goessner** [comment]
Hmm ... now with Version 2.5, but also with 2.4 I will see

![grafik](https://user-images.githubusercontent.com/4902746/84598867-044cd080-ae6e-11ea-84f2-9e0db0e8c609.png)

with your display mode formulas, which seems to be ok for me ...

thanks
