### ISSUE TITLE
Incorrect highlight when math contains multiple lines

### ISSUE THREAD

**Issue by jwhj** [goessner/mdmath#90]
### Summary

When I type math that contains multiple lines, for example,
```
$$
a=b+c
$$ asdf
```
I get incorrect highlight.

### Expected behavior

"a=b+c" is highlighted, while "asdf" is not.

### Actual behavior

"asdf" gets highlighted, while "a=b+c" doesn't.

### Environment

```text
     Operating system: Windows 10 64bit
       VSCode version: 1.42.1
Markdown+Math version: 2.4.0
```

**Comment by ElasticBottle** [comment]
Have you tried putting `asdf` on a new line?

**Comment by jwhj** [comment]
> Have you tried putting `asdf` on a new line?

Well, in that case, neither "a=b+c" nor "asdf" is highlighted.

**Comment by ElasticBottle** [comment]
Weird, works for me. I'm on vs code ver 1.45.1 so maybe that makes a difference. Same ver for markdown + math

**Comment by goessner** [comment]
Syntax highlighting works on basis of tokens and grammars and is completely different from markdown parsing.

So I implemented a poor man's syntax highlighting for latex formulas some time ago (`dollars` namespace only), which breaks with multiline formulas. I had a look into that stuff more intensively twice, but no success.

Maybe sometime in future I get a solution for this accidentially or with a little help of a smarter soul than me.

Personally I can live very well with single line display mode math, as in this example

![grafik](https://user-images.githubusercontent.com/4902746/84599276-27c54a80-ae71-11ea-90a1-be6f1df40182.png)

VSCode does line breaks automatically for me here.

BTW: You would have been able to read about this effect under FAQ's in `readme.md`.

thanks
