### ISSUE TITLE
Regression on "Saving Markdown + Math to file"

### ISSUE THREAD

**Issue by StopMotionCuber** [goessner/mdmath#91]
### Summary
I'm having some regression with this plugin that does not allow to save Markdown+Math to File.

### Expected behavior
HTML file is created next to the normal file

### Actual behavior
HTML File is not created, but an error box is shown.
This Error Box has the the Content `Markdown + Math: Saving html failed:` (yes, there is no reason shown afterwards)

### Steps to reproduce

1. Open Workspace
2. Create Markdown File with some content
3. Save this file e.g. as `Test.md`
4. Command Palette -> `Markdown: Save Markdown+Math to HTML`

### Code example
I could reproduce this issue with text only, so it seems like the content is not relevant

### Environment

```text
     Operating system: Manjaro with Kernel 5.6.15/macOS Catalina
       VSCode version: 1.46.0
Markdown+Math version: 2.4.0
```
### Additional Information
I tried this on older VSCode Versions, 1.45.* also seems to be broken, but on 1.44.2 the bug did not occur.

Also, Copy Markdown+Math to Clipboard is not affected by this bug, so manually creating the file and pasting the content works.

**Comment by goessner** [comment]
Hmm ... you need to save your document first and give it a name. Saving to HTML will keep that name then and only change the extension. This does not work with still untitled documents.

But you are right of course, that you should get a descriptive error message in this case.

I was not aware of the fact, that with macOS no error message is seen.

With version 2.5 now you will get (OS-independent):
```
Markdown+Math: Saving html failed: current untitled markdown document needs to be saved once first!
```
Other error messages with saving are also more detailed now.

thanks

**Comment by StopMotionCuber** [comment]
I don't think that was the actual error, my document _had_ a name (I see that I did not include that in the steps to reproduce, sorry about that).
Also, it was not only on macOS that there was no error message, but also on Manjaro. I just included bot OS-es as I tested both and both were affected (also to check whether there is a configuration issue).

Thanks for looking into the issue, seems like I'm getting errors when installing this extension manually, so I will test it when the new version is available on VSCode Marketplace and reopen the issue in case the issue persists.

**Comment by StopMotionCuber** [comment]
I have just tested this again on Manjaro, and it still fails without error message.
Unfortunately I cannot re-open the issue, so @goessner I'd be happy if you could re-open it.

**Comment by goessner** [comment]
Reopened ... can you please give me more info.

Unfortunatelly I personally have no access to MacOS nor to Manjaro. But the ill-behavior should not be OS-specific.

**Comment by StopMotionCuber** [comment]
#92 fixes the issue

**Comment by goessner** [comment]
should have read #92 first, before  reopening ...
