### ISSUE TITLE
The fllowing text will make other plug-ins unusable

### ISSUE THREAD

**Issue by mengsuenyan** [goessner/mdmath#93]
- $m$\{112,128,192,256,512\}$中选择一个大于$t$的最小整数$t'$, 然后从$\{163,233,239,283,409,571\}$中选择一个满足$2t\lt m \lt 2t'$的整数作为$m$;

![1](https://user-images.githubusercontent.com/49850817/84994904-f48b0000-b17d-11ea-8af4-a507ca537dfe.png)
![2](https://user-images.githubusercontent.com/49850817/84994926-fb197780-b17d-11ea-8b3a-5f70027b159d.png)
![3](https://user-images.githubusercontent.com/49850817/84994932-fd7bd180-b17d-11ea-8a1c-4b76eb400bd7.png)
![4](https://user-images.githubusercontent.com/49850817/84994946-ff459500-b17d-11ea-9a65-295c80f87ca0.png)
![5](https://user-images.githubusercontent.com/49850817/84994959-010f5880-b17e-11ea-8972-55773779ec03.png)

[test.zip](https://github.com/goessner/mdmath/files/4797187/test.zip)

**Comment by goessner** [comment]
There is a new user setting `outerspace` with mdmath version 2.6. This requires inline math enclosed in a space pair.

Default value is `false` for backward compatibility.

Please note, that with changing this setting, VSCode has to be restarted.

Formula syntax highlighting is rigidly static and not modifyable by users.

thanks
