### ISSUE TITLE
Notification every time html file is generated and saved. Extremely annoying.

### ISSUE THREAD

**Issue by bluebalam** [goessner/mdmath#94]
### Summary

There is a pop-up notification in VS code that the generated `html` file was saved every time is saved. This is extremely annoying. There is no visible setting in the extension to turn the notification off.

### Expected behavior

No notification that the html has been saved or perhaps an error notification when generating and saving the html file fails.

### Actual behavior

Pop-up annoying notification, no option in settings to turn it off.

### Steps to reproduce

1. Enable autosave to html
2. Save the md file
3. Pop-up notification of saving file every time there is a manual or auto save

### Code example

N/A

### Related links

N/A

### Environment

```text
     Operating system: macos
      VSCode version: 1.46.1
      Markdown+Math version: v2.5.1
```

**Comment by goessner** [comment]
There is a new mdmath user setting `silent` with version 2.6. Setting it to `true` will suppress user notification on save.

Default valuie is `false` for backward compatibility.

thanks
